### ISSUE TITLE
Wrong client microversion (X-Openstack-Nova-Api-Version) for volume type with multiattach option enabled

### ISSUE THREAD

**Issue by pawcykca** [terraform-provider-openstack/terraform-provider-openstack#1057]
### Terraform Version
```
Terraform v0.13.2
+ provider registry.terraform.io/terraform-providers/openstack v1.31.0
```

### Affected Resource(s)
- openstack_compute_instance_v2

### Terraform Configuration Files
```hcl
resource "openstack_blockstorage_volume_v3" "bastion01_vol01" {
  name = "bastion01_vol1"
  size = "20"
  image_id = var.open_stack_image_id
  enable_online_resize = true
  volume_type = "gp-ceph-nolimit"
  availability_zone = "az1-sse6"
}

resource "openstack_compute_instance_v2" "bastion01" {
  name            = "bastion01"
  flavor_id       = var.open_stack_flavor_id
  key_pair        = "czk-devops"
  security_groups = ["allow_all_out","allow_ssh_in_from_ca","allow_icmp"]
  availability_zone = "az1-sse6"

  block_device {
    uuid                  = openstack_blockstorage_volume_v3.bastion01_vol01.id
    source_type           = "volume"
    boot_index            = 0
    destination_type      = "volume"
    delete_on_termination = false
  }

  network {
    name = "cloud_testnet"
  }
}
```

### Debug Output
https://gist.github.com/pawcykca/65bfcf964a6e2b19125ce7e0f91c6e7f

### Expected Behavior
What should have happened?

The Terraform Openstack Provider should have realized that the volume type of volume defined in `block_device` section has  multiattach option enabled and choose correct microversion for compute endpoint (set `X-Openstack-Nova-Api-Version` header).

or

There should be a ability do define microversion for selected service endpoints.

### Actual Behavior
What actually happened?

The Terraform Openstack Provider sends the default microsversion for the compute endpoint (does not set the `X-Openstack-Nova-Api-Version` header) and the operation fails.
```
openstack_compute_instance_v2.bastion01: Creating...

Error: Error creating OpenStack server: Bad request with: [POST https://my-cloud:13774/v2.1/servers], error message: {"badRequest": {"code": 400, "message": "Multiattach volumes are only supported starting with compute API version 2.60."}}

  on instances.tf line 13, in resource "openstack_compute_instance_v2" "bastion01":
  13: resource "openstack_compute_instance_v2" "bastion01" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create volume type with multiattach option enabled
```
$ cinder type-create gp-ceph-nolimit
$ cinder type-key gp-ceph-nolimit set multiattach="<is> True"
```
2. Create volume and instance based on this volume type (as in 'Terraform Configuration Files' section above)

**Comment by nikParasyr** [comment]
Closing this. Resolved by #1542
