### ISSUE TITLE
Terraform support of backup node for load balancer 

### ISSUE THREAD

**Issue by ArtTverdakhleb** [terraform-provider-openstack/terraform-provider-openstack#1074]
Hi there,
Since the new Octavia driver for LB released there are a couple of long-waited features we want to use. 
One of them: https://github.com/sapcc/octavia-f5-provider-driver/issues/37
We need the ability to define a member address (in the local network ) that gets all traffic in case all regular pool members down, so-called backup node.

**Comment by kayrus** [comment]
We can start implementing this feature once [this PR](https://github.com/gophercloud/gophercloud/pull/2056) is merged.

**Comment by ArtTverdakhleb** [comment]
Hi @kayrus 
Any news on the feature?

Best regards,
Artsiom

**Comment by nikParasyr** [comment]
Hi,

I'm also interested in this one. I'll be working on this later today/tomorrow. Hopefully it'll land on next release

**Comment by TheEvilCoder42** [comment]
Hi @nikParasyr

Could you implement the same as #1227 for `openstack_lb_member_v2` ?

Thanks for your work!
