### ISSUE TITLE
Networking quota cannot be managed by region

### ISSUE THREAD

**Issue by rodcloutier** [terraform-provider-openstack/terraform-provider-openstack#1104]
Networking Quotas are bound to project and region. The same project can have different quotas in each region.

Different clients witll be returned for each region, as presented here.

https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/e33bbfb06108f6b3538ee8d61a97524149ede439/openstack/resource_openstack_networking_quota_v2.go#L101

Currently, each quota managed returns the same id (the project id) which makes it impossible to manage quotas for the same project across multiple regions.

https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/e33bbfb06108f6b3538ee8d61a97524149ede439/openstack/resource_openstack_networking_quota_v2.go#L134

We can try to import the current quotas but each region returns the same id even though the quota values differ.

**Comment by ozerovandrei** [comment]
It can be managed but it should be done in separated directories (so Terraform will use separated states).

But yeah, ID can be changed to use this form for example: `id_region`.
This change should also be backward compatible so we should parse `id` or `id_region` forms of quota ID so current users won't be affected by that change.
