### ISSUE TITLE
json: cannot unmarshal array into Go struct field response.versions of type utils.versionsResp

### ISSUE THREAD

**Issue by J4cKn1X** [terraform-provider-openstack/terraform-provider-openstack#1112]
Hi all,

I am evaluating Openstack and Terraform and facing issues with deploying resources (of any kind) with the "out-of-the-box" installations.

### OS Version
Ubuntu 20.04

### Openstack Version
default installation described here: https://microstack.run/docs
Microstack (latest: Ussuri)
beta channel
devmode

### Terraform Version
tested Terraform v0.12.29 and v0.14.0

### Affected Resource(s)
any

### Terraform Configuration File - main.tf
```
terraform {
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 1.33"
    }
  }
}
provider "openstack" {
  user_name   = "foo"
  tenant_name = "bar"
  password    = "foo_pwd"
  auth_url    = "http://172.22.2.5:8774/v2.1 "
  region      = "some_region"
}
resource "openstack_compute_instance_v2" "tftest" {
  name            = "tftest"
  image_id        = "b6dc5886-8f40-44d3-86f0-8e485b028b0c" # default CirrOS image
  flavor_id       = "1"
  key_pair        = "default_key"
  security_groups = ["default"]
}
```

### Debug Output
https://gist.github.com/J4cKn1X/86f2fff6aaea6fc354b728b8127d2af0
![screenshot](https://user-images.githubusercontent.com/10271934/101342184-7e409e00-3882-11eb-85fd-bc02dffb9ba8.png)

### Expected Behavior
creation of computing instance :tada:

### Actual Behavior
Error :disappointed: 

### Steps to Reproduce
1. install openstack as described in the official docs (https://microstack.run/docs)
2. define main.tf as shown above
3. terraform init
4. terraform apply

Thanks for your help in advance!

**Comment by guilhermesteinmuller** [comment]
Yeah I'm facing the exact issue.

**Comment by jtopjian** [comment]
@J4cKn1X I think the issue is with the `auth_url` you're using:

```hcl
provider "openstack" {
  user_name   = "foo"
  tenant_name = "bar"
  password    = "foo_pwd"
  auth_url    = "http://172.22.2.5:8774/v2.1 "
  region      = "some_region"
}
```

Port 8774 is for the Nova service, not the Keystone service. You can determine the correct auth url by:

* Visiting the Horizon dashboard and looking under the API section
* Looking at an `openrc` file you've already downloaded.

@guilhermesteinmuller Let me know if this helps, too. I suspect the core cause of the problem is that the wrong URL is being used for authentication. The `utils.versionsResp` error is being triggered [here](https://github.com/gophercloud/gophercloud/blob/105a9694c07417728e1c8616497aeef7e192d2b0/openstack/client.go#L98) and [here](https://github.com/gophercloud/gophercloud/blob/19abc56a8cd8d3630ab9735173cb92c0bf635f33/openstack/utils/choose_version.go#L26) when OpenStack is trying to authenticate

**Comment by J4cKn1X** [comment]
Hi @jtopjian 

you are right... its working now as expected. thank you.

**Comment by guilhermesteinmuller** [comment]
> @J4cKn1X I think the issue is with the `auth_url` you're using:
> 
> ```terraform
> provider "openstack" {
>   user_name   = "foo"
>   tenant_name = "bar"
>   password    = "foo_pwd"
>   auth_url    = "http://172.22.2.5:8774/v2.1 "
>   region      = "some_region"
> }
> ```
> 
> Port 8774 is for the Nova service, not the Keystone service. You can determine the correct auth url by:
> 
>     * Visiting the Horizon dashboard and looking under the API section
> 
>     * Looking at an `openrc` file you've already downloaded.
> 
> 
> @guilhermesteinmuller Let me know if this helps, too. I suspect the core cause of the problem is that the wrong URL is being used for authentication. The `utils.versionsResp` error is being triggered [here](https://github.com/gophercloud/gophercloud/blob/105a9694c07417728e1c8616497aeef7e192d2b0/openstack/client.go#L98) and [here](https://github.com/gophercloud/gophercloud/blob/19abc56a8cd8d3630ab9735173cb92c0bf635f33/openstack/utils/choose_version.go#L26) when OpenStack is trying to authenticate

@jtopjian  Yep! I figured out, with your help, that the way I was defining the variables that compose my keystone endpoint was wrong! 

Thank you very much for your time!
