### ISSUE TITLE
openstack_compute_volume_attach_v2 - Error creating OpenStack block storage client: No suitable endpoint could be found in the service catalog.

### ISSUE THREAD

**Issue by n1kofr** [terraform-provider-openstack/terraform-provider-openstack#1123]
Hi,

We are facing an issue with the Openstack provider since we upgraded from 1.32 to 1.34.1

### Terraform Version
terraform=0.12.28
openstack=1.34.1

### Affected Resource(s)
- openstack_compute_volume_attach_v2 

### Expected Behavior
What should have happened?

With previous version of Openstack provider, the volume was properly attached to the VM. 

### Actual Behavior
What actually happened?

With latest version of the provider (Same Terraform version and same Terraform files), we have the following error:

Error: Error creating OpenStack block storage client: No suitable endpoint could be found in the service catalog.

  on modules/common/vm_controller.tf line 68, in resource "openstack_compute_volume_attach_v2" "ota-iso":
  68: resource "openstack_compute_volume_attach_v2" "ota-iso" {

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

We are running Openstack Newton, there is no Block Storage V3 API in our deployment.

### References

The issue we are facing seems related to the change which occurred here:

https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1106

The creation of the openstack_compute_volume_attach_v2  is using a BlockStorageV3Client only and in our deployment we have only BlockStorage V2.

It is working fine with Openstack Provider version 1.32

**Comment by ozerovandrei** [comment]
You will be able to use `vendor_options.ignore_volume_confirmation` argument of the `openstack_compute_volume_attach_v2 ` resource starting from `1.35.0` version of the provider.

That version will be released in a week or so.
