### ISSUE TITLE
Create a subnet with tags argument fail with "Ressource not found".

### ISSUE THREAD

**Issue by goldpanic** [terraform-provider-openstack/terraform-provider-openstack#1166]
Hi,

I'm not able to create subnet with tag argument. Fail with `Ressource not found`.

### Terraform Version
0.14.3

### Affected Resource(s)
openstack_networking_subnet_v2

### Terraform Configuration Files
```hcl
resource "openstack_networking_subnet_v2" "test_sub" {
  count = 1

  network_id      = "<network_id>"
  region          = "<REGION>"

  name            = "test_1"
  cidr            = "10.99.100.0/24"
  dns_nameservers  = ["8.8.8.8","1.1.1.1"]

  tags            = ["test", "dev", "tf"]
}
```

### Expected Behavior
Terraform should create the subnet with a tags associated to it.

### Actual Behavior
After confirm apply, terraform ends with `Resource not found` error.
**This issue only happen when using the tags argument.** When I remove it, the subnet is correctly created.

```hcl
Error: Error creating openstack_networking_subnet_v2: Resource not found

  on main.tf line 50, in resource "openstack_networking_subnet_v2" "test_sub":
  50: resource "openstack_networking_subnet_v2" "test_sub" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by kayrus** [comment]
@goldpanic most probably the tag extension is not enabled in your environment. Can you share the output of the command below?

```sh
openstack extension list --network | grep tag
```

**Comment by goldpanic** [comment]
@kayrus. Here is the output. Provider is OVH.
| Tag support                     | tag                       | Enables to set tag on resources.

**Comment by kayrus** [comment]
I suppose you need a `tag-ext` extension enabled:
```
$ openstack extension list --network | grep tag
| Tag support                                                                                  | tag                         | Enables to set tag on resources.                                                                                                                         |
| Tag support for resources with standard attribute: trunk, policy, security_group, floatingip | standard-attr-tag           | Enables to set tag on resources with standard attribute.                                                                                                 |
| Tag support for resources: subnet, subnetpool, port, router                                  | tag-ext                     | Extends tag support to more L2 and L3 resources.                                                                                                         |
```

**Comment by goldpanic** [comment]
That's seems to be the true.
According to your output it's probably because of this missing extension.
 Thank you for your help. I assume we can close the issue.
