### ISSUE TITLE
Remove deprecated GetOkExists

### ISSUE THREAD

**Issue by ozerovandrei** [terraform-provider-openstack/terraform-provider-openstack#1188]
Usage of `GetOkExists` is discouraged in SDK V2 due to undefined behaviors and may beremoved in a future version of the SDK.

https://github.com/hashicorp/terraform-plugin-sdk/blob/v2.4.4/helper/schema/resource_data.go#L106

SDK V2 will be merged in https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1139

**Comment by kayrus** [comment]
An alternative is to use `GetRawConfig`
