### ISSUE TITLE
A change in user_data results in the destruction of the instance

### ISSUE THREAD

**Issue by DeepBlueMussel** [terraform-provider-openstack/terraform-provider-openstack#1190]
Hi,

Not sure if this concerns this provider directly of Terraform itself.

When updating instance's user_data, TF want's to destroy it on apply, which is not relevant everytime and can bring some 
serious headaches when this user_data comes from a template that is shared for multiple instances.

This issue is discussed in several places, mainly in official [tf aws provider](https://github.com/hashicorp/terraform-provider-aws/pull/7863).

### Terraform Version
Terraform v0.14.7

### Affected Resource(s)
- opc_instance

### Expected Behavior
Do not force destroy the instance when user_data has changed.

### Actual Behavior
Instance is destroyed.

### References
external issue from official tf aws provider
https://github.com/hashicorp/terraform-provider-aws/pull/7863

**Comment by ozerovandrei** [comment]
Hello. Could you please try the following: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/123#issuecomment-335544186

https://www.terraform.io/docs/language/meta-arguments/lifecycle.html

**Comment by DeepBlueMussel** [comment]
Hello, I did try ignore_changes but not with user_data attribute and it just works as expected!
Thanks, I assume that is an acceptable solution to this issue. Can be closed.
