### ISSUE TITLE
Add Support for darwin_arm64

### ISSUE THREAD

**Issue by tibeer** [terraform-provider-openstack/terraform-provider-openstack#1192]
Hi there,

I would like to ask if it is possible to add releases for darwin_arm64. This would help using terraform on Apple's M1 silicon.

Thanks and kind regards
tibeer

**Comment by kayrus** [comment]
Should be possible by bumping go version to 1.16

**Comment by ozerovandrei** [comment]
Will be available in the `1.40.0` release.
