### ISSUE TITLE
OS_DEBUG=1 and TF_LOG=DEBUG

### ISSUE THREAD

**Issue by till** [terraform-provider-openstack/terraform-provider-openstack#1203]
Is there an interest to change the behaviour of `OS_DEBUG`? 

I want to propose the following:

 - user sets `TF_LOG=debug` (or higher)
 - enable `OS_DEBUG=1` by default

I can try to write a PR since we use this provider a lot, would be happy to contribute to it. I often find myself struggling with errors otherwise, and I almost always have to `OS_DEBUG=1` to find out what the nature of the problem is anyway.

**Comment by frittentheke** [comment]
To me somewhat aligning the OS provider debug logging with the terraform TF_LOG setting seems a great idea!
