### ISSUE TITLE
unexpected new value for instance ressource that forces replacement of all instances

### ISSUE THREAD

**Issue by DeepBlueMussel** [terraform-provider-openstack/terraform-provider-openstack#1226]
Hello,

I am facing a serious problem that affects all the instances created with TF.
During the plan, for `openstack_compute_instance_v2` the field `"image_name"` become`"Image not found" -> "Ubuntu 20.04"`. While in the terraform.tfstate it is well at "Ubuntu 20.04". This means that all instances will be destroyed!
The code has not changed since the last apply.

### Terraform Version
Terraform v0.14.8
+ provider registry.terraform.io/ovh/ovh v0.10.0
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.37.0.

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_instance_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output
```
module.data_sb_1.openstack_compute_instance_v2.instance: Refreshing state... [id=8cef6e69-e8e5-4e83-8500-d3cec8aedfc9]
2021/04/12 16:48:59 [WARN] Provider "registry.terraform.io/terraform-provider-openstack/openstack" produced an unexpected new value for module.data_sb_1.openstack_compute_instance_v2.instance during refresh.
      - .image_name: was cty.StringVal("Ubuntu 20.04"), but now cty.StringVal("Image not found")
```

### Expected Behavior
No ressources to create/delete/change.

### Actual Behavior
Instances are replaced because image_name is changing.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by DeepBlueMussel** [comment]
It come the cloud provider who changed the image so the id changed.

**Comment by kidmis** [comment]
@DeepBlueMussel, I'm experiencing the same issue with openstack provider and ovh cloud. Could you clarify how did you fixed the issue?

**Comment by kayrus** [comment]
You need to use terraform builtin lifecycle meta argument, e.g.:

```hcl
  lifecycle {
    ignore_changes = [
      "user_data",
      "key_pair",
      "image_id",
    ]
  }
```

see more details on https://www.terraform.io/docs/language/meta-arguments/lifecycle.html

**Comment by DeepBlueMussel** [comment]
OVH regularly updates its images, which obviously changes the OpenStack id associated with these images.
In my case I create some instances by retrieving an image by its name (e.g. "Ubuntu 20.04"). The openstack provider will then look for this image and get its id to integrate it in the state file.
Unfortunately if a resource has already been created and the image has been updated, the id of the image that Terraform will find in its state file will not correspond to anything in OpenStack and will therefore find "Not Found" and try to rebuild the resource.
As @kayrus  suggests, using lifecycle will solve the problem.

**Comment by kidmis** [comment]
Thanks guys, `lifecycle` argument has fixed the issue. 

JFYI: in my case OVH didn't changed anything (image_id still the same), and actually I use image_name instead of image_id. The problem was related to the fact that Image Name become empty on OVH side after some time.
