### ISSUE TITLE
Allow specifying a user_id when creating an openstack_compute_keypair_v2

### ISSUE THREAD

**Issue by randomswdev** [terraform-provider-openstack/terraform-provider-openstack#1230]
### Terraform Version
Any supported version

### Affected Resource(s)
- openstack_compute_keypair_v2

### Important Factoids
Starting from Nova microversion 2.10, OpenStack allows to specify a user_id when creating a key pair. the official documentation states that: 

> The user_id for a keypair. This allows administrative users to upload keys for other users than themselves.

I would like to have this field optionally added to the openstack_compute_keypair_v2 in order to expose this functionality to the provider users.

If you are interested in such an enhancement, I can contribute the code.

### References
Some links to the OpenStack documentation:

https://docs.openstack.org/api-ref/compute/?expanded=create-or-import-keypair-detail#create-or-import-keypair
https://docs.openstack.org/nova/latest/reference/api-microversion-history.html#id9

**Comment by kayrus** [comment]
@randomswdev I'd suggest to introduce the user_id support for the https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/data-sources/compute_keypair_v2 data source as well.
