### ISSUE TITLE
Docs for openstack_lb_loadbalancer_v2 say vip_subnet_id is optional

### ISSUE THREAD

**Issue by SvenDowideit** [terraform-provider-openstack/terraform-provider-openstack#1231]
```
resource "openstack_lb_loadbalancer_v2" "lb_1" {
}
```

results in 

```
openstack_lb_loadbalancer_v2.lb_1: Creating...

Error: Error creating openstack_lb_loadbalancer_v2: Missing input for argument [VipSubnetID]

  on loadbalancer.tf line 6, in resource "openstack_lb_loadbalancer_v2" "lb_1":
   6: resource "openstack_lb_loadbalancer_v2" "lb_1" {
```

**Comment by nikParasyr** [comment]
@SvenDowideit just for reference, are you using octavia or not?

**Comment by nikParasyr** [comment]
Clarifying a bit the `openstack_lb_loadbalancer_v2` resource:

The `vip_subnet_id` is required for LBaaS but optional for octavia. This is in the documentation. For octavia **one** of the `vip_subnet_id`, `vip_network_id` or `vip_port_id` need to be specified. For Neutron LBaaS **only** `vip_subnet_id` can and needs to be specified.

In case the udnerlying cloud uses octavia you need to specify `use_octavia = true` in the provider block as mentioned here: https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs#use_octavia

Hope this helps

**Comment by ashkraba** [comment]
Thanks a lot, Nikolaos! It helps me with the same issue! You have marked so important and non-obvious thing.
