### ISSUE TITLE
Support for quotas as a data source

### ISSUE THREAD

**Issue by ba-work** [terraform-provider-openstack/terraform-provider-openstack#1289]
Hi, I wish to use existing quotas as a read-only data source.

There is support for creating/importing quotas as resources, but no way use existing quotas as a data source.

**Comment by ba-work** [comment]
@nikParasyr wow thank you for your work! these have been awesome!

Another feature that would be very useful is if there was a project compute limits data source that could show the current usage, something akin to `openstack limits show --project <blah> --absolute` and the storage/network equivalents.

With this we could validate a tf plan based on the limits the quotas during a plan/apply.

**Comment by nikParasyr** [comment]
@ba-work do you consider this done now? or are there more resources?

**Comment by ba-work** [comment]
This can be considered closed. The only other thing I'd like to improve is the hypervisor data source, that one seems to be missing quite a few useful attributes. But, I can make a new issue and pr for that.
