### ISSUE TITLE
add tags openstack_compute_instance_v2 : terraform apply - Resource not found

### ISSUE THREAD

**Issue by SBatais** [terraform-provider-openstack/terraform-provider-openstack#1306]
Hi there,

### versions
- Terraform v0.13.5
- terraform-provider-openstack/openstack v1.44.0

### affected Resource(s)
- openstack_compute_instance_v2

I'm trying to add tags to existing ressources openstack_compute_instance_v2 with terraform. 
The 'terraform plan' step indicates that the tags will be added:

```
Terraform will perform the following actions:
  # openstack_compute_instance_v2.platformgateway[0] will be updated in-place
  ~ resource "openstack_compute_instance_v2" "platformgateway" {
...
      + tags                = [
          + "env=develop",
        ]
```

 but at the 'terraform apply' step, I get the following error:

`Error: Error setting tags on openstack_compute_instance_v2 40c2ac49-b0a3-4936-abd5-5fd9bde97b08: Resource not found`

### terraform debug
```
2021/11/03 08:00:00 [DEBUG] openstack_compute_instance_v2.platformgateway[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: Error setting tags on openstack_compute_instance_v2 40c2ac49-b0a3-4936-abd5-5fd9bde97b08: Resource not found
2021/11/03 08:00:00 [ERROR] eval: *terraform.EvalApplyPost, err: Error setting tags on openstack_compute_instance_v2 40c2ac49-b0a3-4936-abd5-5fd9bde97b08: Resource not found
2021/11/03 08:00:00 [ERROR] eval: *terraform.EvalSequence, err: Error setting tags on openstack_compute_instance_v2 40c2ac49-b0a3-4936-abd5-5fd9bde97b08: Resource not found
```

**Comment by SBatais** [comment]
Can I have a feedback for this issue ?

**Comment by nikParasyr** [comment]
From the logs it seems that instance `40c2ac49-b0a3-4936-abd5-5fd9bde97b08` cannot be found.
Can you make sure that you use the right creds and that the instance is there?
Also can you run with additional logs as described here: https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs#additional-logging and provide the output

**Comment by SBatais** [comment]
I'm sure that I'm using the right credentials and that the instance is there. 
I get the following error during the 'terraform apply' step:
```
openstack_compute_instance_v2.endpoint[0]: Modifying... [id=25180342-e1f8-45ad-9f83-8927161eba35]
Error: Error setting tags on openstack_compute_instance_v2 25180342-e1f8-45ad-9f83-8927161eba35: Resource not found
  on 04_endpointm2m.tf line 15, in resource "openstack_compute_instance_v2" "endpoint":
  15: resource "openstack_compute_instance_v2" "endpoint" {
```
and the following terraform traces:
```
2021-11-17T09:40:00.274Z [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/17 09:40:00 [DEBUG] OpenStack Endpoint for compute: https://ecs.eu-west-0.prod-cloud-ocb.orange-business.com/v2/971e93e1d7004d5a883d81b65a23286c/: timestamp=2021-11-17T09:40:00.274Z
2021-11-17T09:40:00.274Z [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/17 09:40:00 [DEBUG] OpenStack Request URL: PUT https://ecs.eu-west-0.prod-cloud-ocb.orange-business.com/v2/971e93e1d7004d5a883d81b65a23286c/servers/25180342-e1f8-45ad-9f83-8927161eba35/tags: timestamp=2021-11-17T09:40:00.274Z
2021-11-17T09:40:00.275Z [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/17 09:40:00 [DEBUG] OpenStack Request Headers:
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Openstack-Api-Version: compute 2.26
User-Agent: HashiCorp Terraform/0.13.5 (+https://www.terraform.io) Terraform Plugin SDK/2.7.1 gophercloud/2.0.0
X-Auth-Token: ***
X-Openstack-Nova-Api-Version: 2.26: timestamp=2021-11-17T09:40:00.274Z
2021-11-17T09:40:00.275Z [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/17 09:40:00 [DEBUG] OpenStack Request Body: {
  "tags": [
    "env=develop"
  ]
}: timestamp=2021-11-17T09:40:00.275Z
2021-11-17T09:40:00.292Z [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/17 09:40:00 [DEBUG] OpenStack Response Code: 404: timestamp=2021-11-17T09:40:00.292Z
2021-11-17T09:40:00.292Z [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/17 09:40:00 [DEBUG] OpenStack Response Headers:
Connection: keep-alive
Content-Type: application/json
Date: Wed, 17 Nov 2021 09:40:00 GMT
Server: api-gateway
X-Request-Id: 5df27f6947ffddf142aa446bc607f65e: timestamp=2021-11-17T09:40:00.292Z
2021-11-17T09:40:00.292Z [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/17 09:40:00 [DEBUG] OpenStack Response Body: {
  "error_code": "APIGW.0101",
  "error_msg": "The API does not exist or has not been published in the environment",
  "request_id": "5df27f6947ffddf142aa446bc607f65e"
}: timestamp=2021-11-17T09:40:00.292Z
2021/11/17 09:40:00 [DEBUG] openstack_compute_instance_v2.endpoint[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: Error setting tags on openstack_compute_instance_v2 25180342-e1f8-45ad-9f83-8927161eba35: Resource not found
```
thanks in advance for your help

**Comment by nikParasyr** [comment]
are you setting `OS_DEBUG=1` as well? im missing some details on the requests made to openstack.

But with the logs above im not sure if you support the required version for tags which is `2.52`. have you used tags before on other instances?
Can you check it please by running the following commands:
```
## On a terminal with creds and the openstack cli
$ export OS_TOKEN=`openstack token issue -c id -f value`
$ curl -g -i -X GET https://YOUR_OPENSTACK_ENDPOINT:8774
{"versions": [{"status": "SUPPORTED", "updated": "2011-01-21T11:33:21Z", "links": [{"href": "https://YOUR_OPENSTACK_ENDPOINT::8774/v2/", "rel": "self"}], "min_version": "", "version": "", "id": "v2.0"}, {"status": "CURRENT", "updated": "2013-07-23T11:33:21Z", "links": [{"href": "https://YOUR_OPENSTACK_ENDPOINT::8774/v2.1/", "rel": "self"}], "min_version": "2.1", "version": "2.72", "id": "v2.1"}]}

```
The version on the output should be `>= 2.52`, in this example its `2.72`

**Comment by SBatais** [comment]
I will check again if I well set `OS_DEBUG=1`

It's the first time that I'm trying to add tags on ressources created with the terraform openstack provider, on the flexible Engine cloud provider.


I'm not able to retrieve the API version. I get this reply:
```
{
	"versions": [
		{
			"min_version": "",
			"links": [
				{
					"rel": "self",
					"href": "https://ecs.eu-west-0.prod-cloud-ocb.orange-business.com/v2/"
				}
			],
			"id": "v2.0",
			"updated": "2011-01-21T11:33:21Z",
			"version": "",
			"status": "SUPPORTED"
		}
	]
}
```

**Comment by nikParasyr** [comment]
I cant be 100% sure that the issue is the  supported api microversion without the proper output. 
Maybe you could contact the cloud provider and ask them what is the maximum microversion that their nova supports. They should be able to answer you.

**Comment by qukuijin1989** [comment]
hi @nikParasyr  
please check the openstack nova api :https://docs.openstack.org/api-ref/compute/
Lists tags, creates, replaces or deletes one or more tags for a server, checks the existence of a tag for a server.

### **Available since version 2.26**
but the openprovider use the api versino 2.0
![image](https://user-images.githubusercontent.com/73597526/143280689-95c6fb1a-1b0f-47f3-a45c-38ef35276dd3.png)
![image](https://user-images.githubusercontent.com/73597526/143280851-92fce3c0-31c0-4a4d-9dfb-1a9163587444.png)

@SBatais

**Comment by nikParasyr** [comment]
@qukuijin1989 
Thanks for the info. I wasnt aware of this extra api but you are right and we actually use it for [updating instance tags](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_compute_instance_v2.go#L1021-L1027).

Well this means at least `2.26` needs to be supported. And on creation we use the one that requires 2.52 => https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_compute_instance_v2.go#L525, which is a bit unfortunate.

Moreover the error message in the logs is custom:
```
  "error_code": "APIGW.0101",
  "error_msg": "The API does not exist or has not been published in the environment",
  ```
  So maybe `/servers/{server_id}/tags` is not available?

**Comment by qukuijin1989** [comment]
hi @nikParasyr 
So maybe /servers/{server_id}/tags is not available?  
no,the full request is {end-point}/v2/servers/{server_id}/tags, it means under v2 's api there is no tags function
if we change v2 -->v2.1 it will works, so the main problem is because of the "v2" 
when could  have a patch fix this tags problem?

also please check add tags during the creation of computing instance 

thanks 
@SBatais

**Comment by nikParasyr** [comment]
@qukuijin1989 I dont have time atm to patch this or really find the root cause. IF you find the root cause, you can ofc submit a patch for it.  I ran a simple tag update on a node and:
```
2021-11-25T11:44:18.472+0100 [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/25 11:44:18 [DEBUG] OpenStack Request URL: PUT https://endpoint:8774/v2.1/bc0faf9531054cb3a83e27f6c7657acd/servers/e8af5722-e609-4b8f-a1ba-81c2a468a926/tags: timestamp=2021-11-25T11:44:18.472+0100
2021-11-25T11:44:18.472+0100 [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/25 11:44:18 [DEBUG] OpenStack Request Headers:
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Openstack-Api-Version: compute 2.26
User-Agent: HashiCorp Terraform/0.14.3 (+https://www.terraform.io) Terraform Plugin SDK/2.7.1 gophercloud/2.0.0
X-Auth-Token: ***
X-Openstack-Nova-Api-Version: 2.26: timestamp=2021-11-25T11:44:18.472+0100
2021-11-25T11:44:18.472+0100 [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/25 11:44:18 [DEBUG] OpenStack Request Body: {
  "tags": [
    "hello",
    "test"
  ]
}: timestamp=2021-11-25T11:44:18.472+0100
2021-11-25T11:44:18.822+0100 [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/25 11:44:18 [DEBUG] OpenStack Response Code: 200: timestamp=2021-11-25T11:44:18.822+0100
2021-11-25T11:44:18.822+0100 [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/25 11:44:18 [DEBUG] OpenStack Response Headers:
Content-Length: 27
Content-Type: application/json
Date: Thu, 25 Nov 2021 10:44:18 GMT
Openstack-Api-Version: compute 2.26
Vary: OpenStack-API-Version X-OpenStack-Nova-API-Version
X-Compute-Request-Id: req-7961d89b-5d61-4df6-bba2-7f43fc4bda50
X-Openstack-Nova-Api-Version: 2.26
X-Openstack-Request-Id: req-7961d89b-5d61-4df6-bba2-7f43fc4bda50: timestamp=2021-11-25T11:44:18.822+0100
2021-11-25T11:44:18.822+0100 [INFO]  plugin.terraform-provider-openstack_v1.44.0: 2021/11/25 11:44:18 [DEBUG] OpenStack Response Body: {
  "tags": [
    "hello",
    "test"
  ]
}: timestamp=2021-11-25T11:44:18.822+0100
```

it uses v2.1 correctly plus microversion set. So im not sure what is happening in your environment.

**Comment by qukuijin1989** [comment]
hi @nikParasyr 
please check this image 
![image](https://user-images.githubusercontent.com/73597526/143456353-f83e283d-8b62-447a-9e67-2b68f792f2aa.png)

when i use openstack provier it create a request  with {end-point}/v2/servers/{server_id}/tags ==>v2.
if use the flexible engine provider it create the request with v2.1
@SBatais

**Comment by niuzhenguo** [comment]
@qukuijin1989 If you want to access v2.1 API, you can try to update `compute` endpoint to that version.

**Comment by SBatais** [comment]
I finally succeeded to add tags on compute ressources. 
The solution is to override the endpoint in the terraform configuration file of the openstack provider.
```
endpoint_overrides = {
       "compute" = "https://{end-point}/v2.1/<projectid>/"
       } 
```
My concern now is that the tags are not considered as key/value, but only as key. My terraform code is :

```
resource "openstack_compute_instance_v2" "server1" {
…
  tags = ["key1=value1", "key2=value2"]

}
```

@qukuijin1989 @nikParasyr @niuzhenguo
