### ISSUE TITLE
Downloading image from URL results in 0 bytes images or error (TLS cert expired)

### ISSUE THREAD

**Issue by rossengeorgiev** [terraform-provider-openstack/terraform-provider-openstack#1343]
### Terraform Version
```
$ terraform -v
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.46.0

Your version of Terraform is out of date! The latest version
is 1.1.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
- openstack_images_image_v2

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 1.46"
    }
  }
}

provider "openstack" {
    cloud = "my-openstack"
}

resource "openstack_images_image_v2" "test" {
  name             = "test"
  image_cache_path = ".cache"
  image_source_url = "https://nexusrepo.example.com/repository/openstack-images/test.qcow2"
  container_format = "bare"
  disk_format      = "qcow2"
  visibility       = "private"
}
```

### Debug Output
https://gist.github.com/rossengeorgiev/3e2266c472b53a1d0f95bbc7a9dcf913

### Expected Behavior
Image is uploaded on Openstack correctly

### Actual Behavior
Either error, or success, but 0 byte image

### Steps to Reproduce
```
$ terraform apply -auto-approve
...
openstack_images_image_v2.test: Creating...
╷
│ Error: Error opening file for Image: Error downloading image from "https://nexusrepo.example.com/repository/openstack-images/test.qcow2"
│
│   with openstack_images_image_v2.test,
│   on main.tf line 16, in resource "openstack_images_image_v2" "test":
│   16: resource "openstack_images_image_v2" "test" {
│
╵

$ ls -lah .cache/
total 4.0K
drwx------ 2 centos centos   49 Jan  8 19:58 .
drwxrwxr-x 4 centos centos 4.0K Jan  8 19:58 ..
-rw-rw-r-- 1 centos centos    0 Jan  8 19:58 91f07f4a811617212a5f25178a05c8ec.img
```
Note that `wget https://nexusrepo.example.com/repository/openstack-images/test.qcow2` works as expected.

### Important Factoids
Seems like the issue is related to the download of the image, rather than openstack, given then the cached image file is 0 bytes.

However, this used to work few months back. I used slightly older version of terraform and provider, but updating them made no difference. It seems like this is not related to openstack, since is the only thing that would've changed between when it worked and now.

**Comment by rossengeorgiev** [comment]
Well, I found the issue. It's the certificate. The reason I'm getting a 0 byte image is because the provider fails the TLS connection with invalid certificate. Why did it work before? Nexusrepo used to use an internal cert, but it was changed to Let's Encrypt. The provider uses the certificate in `OS_CACERT`, and therefore works fine for Openstack, but not Nexus.

The workaround is to disable verification with  `export OS_INSECURE=true` as I don't think it possible to provide multiple CA certificates in `OS_CACERT`.

I wasted so much time banging my head on this, and all because there was no clear error message telling me of the invalid certificate. 🤦‍♂️

**Comment by ederst** [comment]
We have this problem too, but I think a different root cause:

What we do is, we upload to more than one OpenStack cloud in parallel on the same host, so the same local cache gets used. And judging by the code:

https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/9575669a6717be5c00e01b14f279f48ee247e73f/openstack/images_image_v2.go#L96-L136

There is nothing preventing parallel downloads, and there are no checks in place on whether the downloaded file has already finished and is something which should be uploaded.

So this leaves us sometimes with either 0 byte uploads, or an upload which is too small; something between 0 and the actual image size.

I think to workaround this it is possible to set `web_download=True`, or download the image once before, or use a different `image_cache_path` for each image with the same download URL.

However, what would probably be nice is that the code where the image is downloaded to the local cache does recognize that there is a download in progress and waits until it has finished and then uploads the fully downloaded image.

We already have some (Python) code in place which does something like this, maybe I can "port" this.

**Comment by rossengeorgiev** [comment]
I've worked around the image_cache issue by setting `parallelism=1`, which is works fine for my CI.

However, there are other issues with `openstack_images_image_v2`:

1. It doesn't detect changes the source image file. Upload image, update source file, run apply, nothing. I would expect the image to get replaced.
2. With image from http source, its tricky, but there needs to be hash field that I can set with the hash I expect. I would then like the provider to check the source file, and the upload file, against that hash. This allows me to use internet images, and rely on a strong hash to ensure I'm not getting a different image

**Comment by kayrus** [comment]
> I wasted so much time banging my head on this, and all because there was no clear error message telling me of the invalid certificate.

@rossengeorgiev the #1579 should print the error causing the image download failure.

> What we do is, we upload to more than one OpenStack cloud in parallel on the same host, so the same local cache gets used.

@ederst ederst a special lock was added to avoid simultaneous file access.

**Comment by rossengeorgiev** [comment]
> @rossengeorgiev What should happen if internet image has been changed and/or you lost your local cache? Let's imagine you have a hash set, TF checks for this has and notices that it's been changed, the resource will be recreated, but the expected hash doesn't correspond the new one.

Great question. I'm thinking something like:

1. No cache file, then download the file again
2. Cache file available
    1. Wait for lock if there is one
    2. (optional) check age of cache file, if it is under a threshold (say 5 minutes), do not attempt check online
    3. Attempt to determine if the file is out of date by sending a request with [If-None-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) and [If-Modified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match). A `304 Not Modified` response means the file is up to date. Meta data will need to be stored in addition to the file, like `ETag` and `Last-Modified`.
    4. Download the file
3. Cache file available, and up to date from the server, then check if hash has changed and update/replace the resource
