### ISSUE TITLE
Can I import openstack_networking_port_secgroup_associate_v2?

### ISSUE THREAD

**Issue by till** [terraform-provider-openstack/terraform-provider-openstack#1353]
I am trying to restore a a few states I deleted 🤦🏼‍♂️ , and one of the resources that popped up in a plan was `openstack_networking_port_secgroup_associate_v2`. I couldn't find much about importing it though — as in what to look for, or how to construct it.

I was also thinking, maybe it's idempotent enough (due to `enforce`) to just re-run my plan and have it import?

### Terraform Version

_latest_

### Affected Resource(s)

- openstack_networking_port_secgroup_associate_v2

### Terraform Configuration Files

```hcl
resource "openstack_networking_port_secgroup_associate_v2" "port_customer" {
  depends_on = [
    data.openstack_networking_secgroup_v2.security_group,
    data.openstack_networking_port_v2.find_port
  ]

  port_id = data.openstack_networking_port_v2.find_port.id
  enforce = "true"

  security_group_ids = data.openstack_networking_secgroup_v2.security_group.*.id
}
```

### Debug Output

n/a

### Expected Behavior

If possible, documentation how to import it.

### Actual Behavior

No documentation available.

**Comment by nikParasyr** [comment]
@till sorry for the late reply. From checking the code i think it can imported by using the the `port_id`.

Im making a PR now to add a test and update docs.
