### ISSUE TITLE
[New] Missing monitor_address and monitor_port Arguments on openstack_lb_members_v2

### ISSUE THREAD

**Issue by flashjmp** [terraform-provider-openstack/terraform-provider-openstack#1360]
Hi there,

we are trying to create load balancer members with a designated monitor port (and address) but the arguments are not available on the TF resource.

### Terraform Version
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.47.0

### Affected Resource(s)
Please list the resources as a list, for example:
(- openstack_lb_member_v2 --> deprecated neutron version)
- openstack_lb_members_v2  --> current Octavia API

### Terraform Configuration Files
```hcl
doesn't really make sense, as the argument is not available
```

### Expected Behavior
monitor_address and monitor_port arguments should be available in TF resource as per API documentation

### Actual Behavior
both arguments (as well as the argument "backup" is missing from the resource

### References
Openstack documentation for openstack.load_balanacer.v2.member: https://docs.openstack.org/openstacksdk/latest/user/resources/load_balancer/v2/member.html#openstack.load_balancer.v2.member.Member

Related Issue Request on gophercloud SDK (--> Applies only to lb_member_v2, the fields are present in the lb_member**s**_v2)
https://github.com/gophercloud/gophercloud/issues/2369

**Comment by corrieriluca** [comment]
Hi,

I would also be interested in this feature, thanks for your ongoing PR!

For context, I encountered this limitation today while trying to reproduce what I was able to do with Horizon: adding a different port for monitoring.

My use case is a pool of MySQL instances, with `mysqlchk` (health-check) running on port 9200.

As an example:

```hcl
resource "openstack_lb_members_v2" "databases" {
  pool_id = openstack_lb_pool_v2.databases.id

  dynamic "member" {
    for_each = openstack_compute_instance_v2.database
    content {
      address       = member.value.network[0].fixed_ip_v4
      protocol_port = 3306
      monitor_port  = 9200 # /!\ not possible yet
    }
  }
}
```

**Comment by flashjmp** [comment]
Hi Luca,
yes, this was almost exactly my use case as well (in my case PostGreSQL Servers :-) )

This is now working with my PR:

´´´

resource "openstack_lb_members_v2" "lb_members" {
   
  pool_id       = openstack_lb_pool_v2.lb_pool_pgsql.id
  
  
  dynamic "member" {
    for_each = openstack_compute_instance_v2.pgsql_server
        
    content {
      name          = "${member.value.name}_lb_member"
      address       = member.value.access_ip_v4
      protocol_port = 22
      monitor_port = 8888
      monitor_address = member.value.access_ip_v4
    }
  }   
}
´´´´

This is the result in the statefile:

´´´
{
      "mode": "managed",
      "type": "openstack_lb_members_v2",
      "name": "lb_members",
      "provider": "provider[\"registry.terraform.io/terraform-provider-openstack/openstack\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "76c50e80-975a-4f8d-88c4-06ba297a4d40",
            "member": [
              {
                "address": "10.114.1.139",
                "admin_state_up": true,
                "backup": false,
                "id": "cff7f83c-55f8-468d-b115-0bf71d0db967",
                "monitor_address": "10.114.1.139",
                "monitor_port": 8888,
                "name": "pgsql3-test_lb_member",
                "protocol_port": 22,
                "subnet_id": "",
                "weight": 1
              },
              {
                "address": "10.114.1.141",
                "admin_state_up": true,
                "backup": false,
                "id": "40b2fb53-8c19-41f8-9f10-e82585ba28f5",
                "monitor_address": "10.114.1.141",
                "monitor_port": 8888,
                "name": "pgsql3-test_lb_member",
                "protocol_port": 22,
                "subnet_id": "",
                "weight": 1
              },
              {
                "address": "10.114.1.145",
                "admin_state_up": true,
                "backup": false,
                "id": "9ed258fa-c5e8-4b04-8795-1e72c135570d",
                "monitor_address": "10.114.1.145",
                "monitor_port": 8888,
                "name": "pgsql2-test_lb_member",
                "protocol_port": 22,
                "subnet_id": "",
                "weight": 1
              }
            ],
            "pool_id": "76c50e80-975a-4f8d-88c4-06ba297a4d40",
            "region": "",
            "timeouts": null
          },
´´´

**Comment by flashjmp** [comment]
Hi @corrieriluca ,
the PR was finally merged today, so if you need it "urgently" you could now build a provider from source...
