### ISSUE TITLE
Maintainers needed

### ISSUE THREAD

**Issue by ozerovandrei** [terraform-provider-openstack/terraform-provider-openstack#1376]
Hello.

Current maintainers of terraform-provider-openstack don't actively work on this project.
I personally haven't been using OpenStack in my day to day work for almost three years.

Because of this I can only do releases if there are some changes and basically that's all for me. 
At least at the current time.

If anyone is interested in helping to support this provider, you can write me an E-Mail.

**Comment by mnaser** [comment]
@ozerovandrei we (at vexxhost) be happy to help maintain this.  can we chat about it?

**Comment by ozerovandrei** [comment]
Currently we have the following maintainers (apart from me):

- @nikParasyr
- @kayrus
- @mnaser
- @okozachenko1203

I'm closing this issue since it's the biggest amount of maintainers that have been in this project from the beginning.
Thank you!
