### ISSUE TITLE
Import acceptance tests with data sources are failing

### ISSUE THREAD

**Issue by nikParasyr** [terraform-provider-openstack/terraform-provider-openstack#1449]
Currently various acceptance tests for `import` that include data sources are failing. This was introduced in `terraform >= 1.3.X`.

Upstream issue: https://github.com/hashicorp/terraform-plugin-sdk/issues/1066

I'll pin tf version to 1.2.9 until it is fixed upstream

**Comment by kayrus** [comment]
@nikParasyr can we already close this issue?

**Comment by nikParasyr** [comment]
I'd like to remove the pinned version and see if the issue is gone. Would prefer to test the latest tf version instead of the pinned. I'll have a look later this week
