### ISSUE TITLE
docs: Wrong attribute name of `instance` for `openstack_db_user_v1`, it should be `instance_id`

### ISSUE THREAD

**Issue by wjkw1** [terraform-provider-openstack/terraform-provider-openstack#1464]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see https://www.terraform.io/community.html.

### Terraform Version

v1.3.3

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_db_user_v1

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Expected Behavior
Copying the attributes on the openstack [docs here](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/db_user_v1#example-usage) should work successfully

### Actual Behavior

When trying to apply using docs attributes, we get below error message. It's showing the wrong attribute name as `instance`, the correct attribute on docs should be `instance_id`

```
│ Error: Missing required argument
│ 
│   on database.tf line 53, in resource "openstack_db_user_v1" "basic":
│   53: resource "openstack_db_user_v1" "basic" {
│ 
│ The argument "instance_id" is required, but no definition was found.
╵
╷
│ Error: Unsupported argument
│ 
│   on database.tf line 55, in resource "openstack_db_user_v1" "basic":
│   55:   instance  = "${openstack_db_instance_v1.kaituhi_db_instance.id}"
│ 
│ An argument named "instance" is not expected here.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

```tf
resource "openstack_db_instance_v1" "basic" {
  region    = "region-test"
  name      = "basic"
  flavor_id = "31792d21-c355-4587-9290-56c1ed0ca376"
  size      = 8

  network {
    uuid = "c0612505-caf2-4fb0-b7cb-56a0240a2b12"
  }

  datastore {
    version = "mysql-5.7"
    type    = "mysql"
  }
}

resource "openstack_db_database_v1" "mydb" {
  name        = "mydb"
  instance_id = "${openstack_db_instance_v1.basic.id}"
}

resource "openstack_db_user_v1" "basic" {
  name      = "basic"
  instance  = "${openstack_db_instance_v1.basic.id}"
  password  = "password"
  databases = ["mydb"]
}
```

**Comment by nikParasyr** [comment]
@wjkw1 thanks for reporting this. made a PR to update docs
