### ISSUE TITLE
compute_instance_v2 not replaced on blockstorage_volume_v3 replacement if disk_size is ignored

### ISSUE THREAD

**Issue by Mazorius** [terraform-provider-openstack/terraform-provider-openstack#1470]
### Terraform Version

1.3.6

### Affected Resource(s)

- openstack_compute_instance_v2
- openstack_blockstorage_volume_v3

### Terraform Configuration Files

```hcl
resource "openstack_blockstorage_volume_v3" "vm_volume" {
  count                = var.node_count
  name                 = "${var.prefix}-${var.dc}-${var.stage}-${var.instance_name}-${count.index + 1}"
  description          = "System volume of ${var.instance_name}-${count.index + 1}"
  size                 = var.disk_size
  enable_online_resize = true
  image_id             = data.openstack_images_image_v2.vm_image.id

  lifecycle {
    ignore_changes = [image_id]
  }
}

resource "openstack_compute_instance_v2" "vm" {
  count               = var.node_count
  name                = "${var.prefix}-${var.dc}-${var.stage}-${var.instance_name}-${count.index + 1}"
  flavor_name         = var.flavor_name
  key_pair            = var.compute_keypair_name
  tags                = []
  stop_before_destroy = true
  user_data           = data.cloudinit_config.vm_user_data[var.instance_name == "gitlab_rails" ? 0 : count.index].rendered

  block_device {
    uuid                  = openstack_blockstorage_volume_v3.vm_volume[count.index].id
    source_type           = "volume"
    volume_size           = var.disk_size
    destination_type      = "volume"
    delete_on_termination = false
  }

  network {
    port = openstack_networking_port_v2.networking_port[count.index].id
  }

  lifecycle {
    ignore_changes = [block_device["volume_size"]]
  }
}
```

### Debug Output

-

### Panic Output

-

### Expected Behavior

Replacement of blockstorage replaces also the compute-instance.

Change of blockstorage-disk-size does not replace the compute-instance.

### Actual Behavior

Replacement of blockstorage **does not** replaces the compute-instance.

Change of blockstorage-disk-size does not replace the compute-instance.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan to check if the instance will be replaced on size or replace`

### Important Factoids

-

### References

-

**Comment by nikParasyr** [comment]
@Mazorius Im sorry this is not very clear to me.

When you plan what is exactly reported?
I see on the volume you have enabled online_resize and you are ignoring the volume_size on the instance resource so if things are working as expected your volume should increase and instance should not be redeployed (that is in theory). What is actually happening when you plan/apply?

Thanks

**Comment by Mazorius** [comment]
@nikParasyr thanks for feedback

The plan/apply works in that case successfully. On disk size change the disk is changed and nothing is replaced.
But as soon as I try to replace the storage, the instance is also not replaced, what in fact I think should happen. As the uuid of the blockstorage is changing.

**Comment by nikParasyr** [comment]
@Mazorius 

Thanks for the info. I think I understand it a bit more now. Unfortunately i dont have access to a system atm that i can test some stuff but I think your `ignore_changes` block might be problematic. Could you test change:
```
  lifecycle {
    ignore_changes = [block_device["volume_size"]]
  }
```

to:
```
  lifecycle {
    ignore_changes = [
      block_device[0]["volume_size"]
    ]
  }
```

Reasoning is that `block_device` can be repeated multiple times thus you need to specify which one you are referring to, in this case 0.

**Comment by Mazorius** [comment]
@nikParasyr syntax must be a little adapted due to:

```plain
│ Error: Invalid index operation
│ 
│   on ../../modules/gitlab_openstack_instance/main.tf line 92, in resource "openstack_compute_instance_v2" "vm":
│   92:       block_device[0]["volume_size"]
│ 
│ Only attribute access is allowed here. Did you mean to access attribute "volume_size" using the dot operator?
```

So it looks like:

```hcl
  lifecycle {
    ignore_changes = [
      block_device[0].volume_size
    ]
  }
```

will test if this works.

**Comment by Mazorius** [comment]
That solved it. Thanks!
