### ISSUE TITLE
Compute v2: Allow power_state of reboot

### ISSUE THREAD

**Issue by aminmr** [terraform-provider-openstack/terraform-provider-openstack#1478]
Hello everyone,

In some scenarios, It's needed to reboot or hard reboot your instance. Unfortunately, The `power_state` arguments don't support the `reboot` state. I need to reboot my instance after the disk resize to apply these changes on the OS. 

#### Terraform Version
‍‍Terraform v1.3.6
on linux_amd64

### Affected Resource(s)
- `openstack_compute_instance_v2`

### Terraform Configuration Files
```hcl
resource "openstack_blockstorage_volume_v3" "root" {

  name                            =  "${var.instance_name}-root-disk"
  enable_online_resize            =  true
  image_id                        =  var.image_id 
  size                            =  var.disk_size
}

resource "openstack_compute_instance_v2" "this" {

  name                   =  var.instance_name
  flavor_name            =  var.flavor_name
  key_pair               =  var.ssh_key_name
  security_groups        =  ["Default"]
  image_id               =  var.image_id

     block_device {
          uuid                          = openstack_blockstorage_volume_v3.root.id
          source_type                   = "volume"
          boot_index                    = 0 
          destination_type              = "volume"  
          delete_on_termination         = true
          }
}
```
### Expected Behavior
The `power_state` has a `reboot` value.

### Actual Behavior
There is no reboot behavior for OpenStack instances.

**Comment by noorbala7418** [comment]
Same issue

**Comment by kayrus** [comment]
`reboot` is not a permanent state, I don't know how it's possible to add this state into a code.
I think that the volume extension issue should be fixed on another level. Certain hypervisors require triggering `echo 1 > /dev/path/to/block/devide/rescan` to update the block device geometry. See how it's done in k8s openstack cloud controller https://github.com/kubernetes/cloud-provider-openstack/blob/c8b849478d67112b2d3a4a428b31bac7d3356eff/pkg/util/blockdevice/blockdevice_linux.go#L110 for example.

**Comment by kayrus** [comment]
There is no way to make the server using terraform, see my comment above. As a workaround you can trigger an API call (I can probably implement a keystone token export within the #638) using https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http. @nikParasyr I think this issue can be closed.
