### ISSUE TITLE
Obscure error when "alias" is provided to provider {}

### ISSUE THREAD

**Issue by EvanCarroll** [terraform-provider-openstack/terraform-provider-openstack#1480]
I got a very obscure error when I provided `alias` to `provider {}`. It would be nice if this was more direct.

https://devops.stackexchange.com/q/17444/18965

----
Using Terraform v1.3.7
provider registry.terraform.io/terraform-provider-openstack/openstack v1.48.0

**Comment by kayrus** [comment]
`alias` is a terraform level option. I gues you used an old version of terraform or old version of terraform-provider-openstack that used an old SDK. Aliases work fine with the recent provider version.

**Comment by Dranaxel** [comment]
Hi,

Using this configuration yields the same error, even with newer config: 

```
terraform {
  required_version = "> 1.10"
  required_providers {
    ovh = {
      source  = "ovh/ovh"
      version = ">= 0.13.0"
    }
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "3.0.0"
    }
    cloudinit = {
      source  = "hashicorp/cloudinit"
      version = "2.3.6-alpha1"
    }
  }
}


provider "openstack" {
  auth_url    = "https://auth.cloud.ovh.net/v3/" # URL d'authentification
  domain_name = "default"
  alias = "ovh"
}

provider "ovh" {
  endpoint = "ovh-eu"
}
```

With these versions:
- tf 1.10.4
- openstack: 3.0.0
- ovh 1.5.0
