### ISSUE TITLE
openstack_images_image_v2 resource not uncompressing dowloaded image

### ISSUE THREAD

**Issue by spnngl** [terraform-provider-openstack/terraform-provider-openstack#1481]
### Affected Resource(s)
- openstack_images_image_v2

### Expected Behavior
- Defining an image resource with an url pointing to a compressed image (for example flatcar ones which have well defined "content-type" headers)
- Uncompress automatically
- Upload uncompressed image

See:
```
$ curl -I "https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_openstack_image.img.bz2"
HTTP/2 200 
server: nginx
date: Wed, 15 Feb 2023 21:56:28 GMT
content-type: application/x-bzip2
content-length: 371091603
etag: "rosr8b64xs43"
last-modified: Fri, 20 Jan 2023 18:26:35 GMT
accept-ranges: bytes

$ curl -I "https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_openstack_image.img.gz"
HTTP/2 200 server: nginx
date: Wed, 15 Feb 2023 21:58:46 GMT
content-type: application/gzip
content-length: 388364110
etag: "rosr8b6f7zny"
last-modified: Fri, 20 Jan 2023 18:26:35 GMT
accept-ranges: bytes
```

### Actual Behavior
Images are uploaded without errors but in their compressed format (tried it with gzip and bz2) which is unusable.

### Steps to Reproduce
Trying to use a compressed image in a  openstack_images_image_v2 resource.

**Comment by kayrus** [comment]
can you share an HCL snippet for your use case?
this is a feature request, right?

**Comment by spnngl** [comment]
Yes, I forgot.

I don't know if it is a feature request or a bug: I read quickly the [code](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/c8ddcb6d83ef40a6f2eef97278b06034e1b1e685/openstack/images_image_v2.go#L86) and find out it's using the [net/http/Client.go](https://cs.opensource.google/go/go/+/refs/tags/go1.20.1:src/net/http/client.go;l=581) which should already uncompress automatically.

Furthermore I'm not using the web_download, it caused timeout everytime whereas when I download myself + upload it is working (minus the compression). I'm using OVHcloud openstack.

Here what I use:
```
resource "openstack_images_image_v2" "flatcar_stable" {
  name              = "Flatcar - current stable"
  region            = "GRA11"
  image_source_url  = "https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_openstack_image.img.gz"
  web_download      = false
  container_format  = "bare"
  disk_format       = "qcow2"                                                                                                                                                                                                                  
  protected         = false
  hidden            = true
  visibility        = "private"
}
```

**Comment by kayrus** [comment]
@spnngl go http client automatically decompresses only the `Content-Encoding` marked data. `Content-Type` header is used for a higher level.

Current logic acts like a regular `wget` or `curl`. If you want to decompress an image, you need to pipe the output to `bzcat`, `xzcat`, `zcat`, `lzcat`, etc.

I think that your request is a feature, not a bug. Would you prefer to implement a `decompress` flag feature to this resource?

It should not be difficult, see https://stackoverflow.com/questions/13130341/reading-gzipped-http-response-in-go for reference.

**Comment by spnngl** [comment]
Just created an MR for decompression handling of gzip and bzip2 here: https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1482
