### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mnaser** [terraform-provider-openstack/terraform-provider-openstack#1484]
Would it be possible to make a new release since the provider has had a few fixes so far? :)

**Comment by ozerovandrei** [comment]
Let's wait for the implementation of https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1489, it's in the progress.

**Comment by maxime1907** [comment]
And also this please 🙂 
- https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1482
