### ISSUE TITLE
OVH IPv6 wrong prefix-length

### ISSUE THREAD

**Issue by Trenrod** [terraform-provider-openstack/terraform-provider-openstack#1506]
### Terraform Version
```sh
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/ovh/ovh v0.28.1
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.50.0
```

### Affected Resource(s)
- openstack_compute_instance_v2

### Terraform Configuration Files
```hcl
# Configure the OpenStack provider hosted by OVHcloud
provider "openstack" {
  auth_url    = "https://auth.cloud.ovh.net/v3/" # Authentication URL
  domain_name = "default"                        # Domain name - Always at 'default' for OVHcloud
  alias       = "ovh"                            # An alias
}

# Create SSH Key (as cannot access exsting)
resource "openstack_compute_keypair_v2" "CloudKey" {
  provider   = openstack.ovh                 # Provider name declared in provider.tf
  name       = "CloudKey"                    # Name of the SSH key to use for creation
  public_key = file("credentials/cloud_pub") # Path to your previously generated SSH key
}

# Creating the instances
resource "openstack_compute_instance_v2" "test_terraform_instance" {
  name        = "testipv6"     # Instance name
  provider    = openstack.ovh  # Provider name
  image_name  = "Ubuntu 22.10" # Image name
  flavor_name = "s1-2"         # Instance type name
  # Name of openstack_compute_keypair_v2 resource named keypair_test
  key_pair = openstack_compute_keypair_v2.CloudKey.name
  network {
    name = "Ext-Net" # Adds the network component to reach your instance
  }
}
```

### Debug Output
https://gist.github.com/Trenrod/1f404686d9c63812377fd53546f164d2

### Panic Output
None

### Expected Behavior
Should create a network address with prefix-length of 128 e.g.
inet6 2001:41d0:701:1000::39d2/128 scope global 

### Actual Behavior
Create a network address with prefix-length of 56 e.g.
inet6 2001:41d0:701:1000::39d2/56 scope global 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
No

### References
No

**Comment by kayrus** [comment]
According to logs, the fixedip is created by cloud provider. Besides where did you get an info about the `/128` or `/56` prefixes?

**Comment by Trenrod** [comment]
It was mentioned in this guide:
https://docs.ovh.com/gb/en/vps/configuring-ipv6/

And I also contacted OVH support. They told me to replace the with 128 prefix-length.
After adjusting the prefix-length manually this works.
```sh
sudo ip addr del 2001:41d0:701:1000::34/56 dev ens3
sudo ip addr add 2001:41d0:701:1000::34/128 dev ens3
```

**Comment by kayrus** [comment]
openstack terraform provider doesn't specify prefixes, they are probably automatically generated by OVH DHCP server.

**Comment by Trenrod** [comment]
Thank you for that clarification. May OVH is interested in fixing it. Will comment for completion once clarified.
