### ISSUE TITLE
Provider-level default_tag

### ISSUE THREAD

**Issue by sebbbastien** [terraform-provider-openstack/terraform-provider-openstack#1507]
Hi,

Please consider providing a provider-level `default_tag` as available on [AWS Provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags).

This can help reducing redundant code and ensuring a good tag coverage.

Best regards,

**Comment by kayrus** [comment]
You're right, this task would require checking the whole provider code. Unfortunately in most OpenStack services tags are enabled as an extension and they're not always enabled by cloud providers. Another factor is that gophercloud might not support tags for certain resources yet, e.g. https://github.com/gophercloud/gophercloud/pull/2492.

Would you like to work on this task?
