### ISSUE TITLE
Ability to remove port from instances.

### ISSUE THREAD

**Issue by aminmr** [terraform-provider-openstack/terraform-provider-openstack#1510]
Hello everyone. Is there any way to unset the port from the OpenStack instance and delete it?

By now in reference to documentation, any change to the network block in `openstack_compute_instance_v2` will replace the instance.
https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_instance_v2#uuid

### Affected Resource(s)
- openstack_compute_instance_v2 
- openstack_compute_port_v2

### Expected Behavior
By deleting the port from the configuration, only the port is deleted, and no instance replacement occurs.

### Actual Behavior
The port is deleted, and the instance is replaced.

**Comment by kayrus** [comment]
@aminmr thanks for the report. This is an expected behavior. I'd recommend you to use the `openstack_compute_interface_attach_v2` resource to attach and detach ports.
Let me know if this suits your case.

**Comment by aminmr** [comment]
Thank you, Kayrus. This solution should work. But I think when you give an existing UUID in the instance creation process, the OpenStack provider should handle this.

**Comment by kayrus** [comment]
The `openstack_compute_instance_v2` resource is really sensitive for modifications. Adding a teeny tiny feature may break the provider for some users with different openstack versions. Like it happened recently with `openstack_compute_servergroup_v2`.

**Comment by aminmr** [comment]
Thank you @kayrus. 
I just checked this solution and it worked but I forgot to update here. Attention to those who faced this issue, you need to set `network_mode` to none. If you do not set this variable you got an error because the instance needs at least one OpenStack port.
And @kayrus I would appreciate if I can help to develop this feature in the `openstack_compute_instance_v2`

**Comment by kayrus** [comment]
I'm closing this issue, since we don't have resources to implement this feature and there is a workaround available.
