### ISSUE TITLE
New decompression flag on openstack_images_image_v2 causes force replacement for existing instances

### ISSUE THREAD

**Issue by rossengeorgiev** [terraform-provider-openstack/terraform-provider-openstack#1522]
### Terraform Version
Terraform v1.3.8
terraform-provider-openstack v1.51.0

### Affected Resource(s)
openstack_images_image_v2

### Expected Behavior
Running `terraform apply` nothing changes

### Actual Behavior
Running `terraform apply` forces replaces existing resources that were created in previous versions of the provider

### Steps to Reproduce
1. Creates images with  `< 1.50`
2. Upgrade provider to `= 1.50`
3. Change another parameter, say `tags`
4. `terraform plan`

The `tags` update will be in-place but `decompressed` will show as `forces replace`

### References
Issue #1481
PR #1482

## Workaround

```hcl
  lifecycle {
    ignore_changes = [
      decompress,
    ]
  }
```

**Comment by kayrus** [comment]
@rossengeorgiev I cannot reproduce an issue. I created an image with 1.49, saved the state and upgraded the provider to 1.51. Terraform hasn't suggested to replace an image.

Here is the diff of my state files:

```diff
--- terraform.tfstate.1.49      2023-03-20 20:28:21.927470003 +0100
+++ terraform.tfstate   2023-03-20 20:29:59.692209541 +0100
@@ -1,7 +1,7 @@
 {
   "version": 4,
   "terraform_version": "1.3.9",
-  "serial": 3,
+  "serial": 4,
   "lineage": "9ef20adb-eb40-3af2-7506-7ccde428d0a3",
   "outputs": {},
   "resources": [
@@ -17,6 +17,7 @@
             "checksum": "1bb922391ea1bc0415fa9ba2cb0e8bcd",
             "container_format": "bare",
             "created_at": "2021-12-01T13:11:34Z",
+            "decompress": null,
             "disk_format": "qcow",
             "file": "/v2/images/6bce2020-2acb-4a5c-a463-74d506e52e97/file",
             "hidden": false,
```

Even if I manually set decompress to "false". If I set decompress to true, then the image should be recreated as expected.

Can you share more details about your issue with examples?

**Comment by rossengeorgiev** [comment]
I should've reproduce this properly. Looks like this behaviour was introduced in `1.50`.  There are two key bits:

- State was generated with version `<=1.49`
- For the force-replacement to happen, another parameter needs to change in-place (e.g. `tags`)

`main.tf`
```hcl
terraform {
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "= 1.49"
    }
  }
}

provider "openstack" { }

resource "openstack_images_image_v2" "images" {
  name             = "cirros-test"
  image_source_url = "http://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img"
  container_format = "bare"
  disk_format      = "qcow2"
  tags             = ["1.49"]
}
```

Then execute:
```
terraform init
terraform apply -auto-approve
sed -i 's/1.49/1.50/g' main.tf
terraform init -upgrade
terraform plan
```

**Comment by kayrus** [comment]
@rossengeorgiev weird bug. I submitted a PR.
