### ISSUE TITLE
Changes to server_group in 1.51 wants to recreate existing groups

### ISSUE THREAD

**Issue by MindTooth** [terraform-provider-openstack/terraform-provider-openstack#1523]
### Terraform Version
Terraform: 1.3.9 (1.4 is broken)
OpenStack Provider: 1..51

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_servergroup_v2

### Terraform Configuration Files
```hcl
resource "openstack_compute_servergroup_v2" "test-sg" {
  name     = "my-sg"
  policies = ["anti-affinity"]
}
```

```hcl
terraform {
  required_version = "~> 1"

  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "1.51.0"
    }
  }
}
```

### Debug Output
https://gist.github.com/MindTooth/23e22ca90d4c0c5dcf36d387d03b9271

### Panic Output
N/A.

### Expected Behavior

Nothing.  The same configuration should not do changes.

### Actual Behavior

Terraform wants to recreate existing server group with the same settings.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Bump provider version from 1.50 to 1.51
1. `terraform plan`

### Important Factoids

Private cloud.  OpenStack Stein.

### References
- GH-1382

**Comment by kayrus** [comment]
I couldn't reproduce an issue. I created a server group with the following code:

```hcl
terraform {
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "1.49.0"
    }
  }
}

resource "openstack_compute_servergroup_v2" "test-sg" {
  name     = "my-sg"
  policies = ["anti-affinity"]
}
```

Then upgraded to 1.51 and terraform plan hasn't produced any changes. I tried both terraform 1.3.9 and 1.4.2.

**Comment by MindTooth** [comment]
So glad that you could reproduce it. 😄  Didn't get the UPD part in my initial reply email and didn't know what to do if you couldn't reproduce it.  Glad you could.

Thanks for the quick fix! 🎉

**Comment by kayrus** [comment]
@MindTooth a new minor release has been published. Let me know if you still have issues with it.
