### ISSUE TITLE
[Feature] data source loadbalancer flavor

### ISSUE THREAD

**Issue by yomovh** [terraform-provider-openstack/terraform-provider-openstack#1530]
My goal is to be able to filter one of the flavor that are provided in  the cli `openstack loadbalancer flavor list` to be able to use it inside the [openstack_lb_loadbalancer_v2](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/lb_loadbalancer_v2) resource

It could look like the following
```hcl
data "openstack_lb_loadbalancer_flavor_v2" "small_flavor"{
       name ="small"
}
```

**Comment by nikParasyr** [comment]
Hello. This needs to be merged upstream on gophercloud https://github.com/gophercloud/gophercloud/pull/2575 before we can start working on this

**Comment by Pyjou** [comment]
This is my plan 😄 
When the PR is merged I've plan to work on that.
