### ISSUE TITLE
[Doc] Facilitate documentation browsing through subcategory usage

### ISSUE THREAD

**Issue by yomovh** [terraform-provider-openstack/terraform-provider-openstack#1533]
The goal of this feature request (that I can implement) is to use of the [subcategory](https://developer.hashicorp.com/terraform/registry/providers/docs#yaml-frontmatter) feature in the YAML frontmatter. 
This should smooth the documentation browsing. 

I propose we use the pattern `Category  / Project code name`. This would be :
* Block Storage / Cinder
* Compute VM / Nova
* Container Infra / Magnum
* Database / Trove
* DNS / Designate
* Networking / Neutron
* Identity / Keystone
* Images / Glance
* Secrets / Barbican
* Load Balancing as a Service / Octavia
* Object Storage / Swift
* Orchestration / Heat
* Shared Filesystem / Manila

Let me know if seems ok for you and I will implement the PR.

**Comment by nikParasyr** [comment]
This is something i was thinking myself as well as the number of resources and data sources have increased.
From my side I would be happy to see a PR making this change. @kayrus ?
