### ISSUE TITLE
[Bug] Terraform tries to reattach a nodegroup to a replaced cluster

### ISSUE THREAD

**Issue by jan-di** [terraform-provider-openstack/terraform-provider-openstack#1541]
The documentation states, that if the `cluster_id` of a nodegroup changes, the nodegroup will be recreated.
Actually, terraform tries to reattach the nodegroup by updating the `cluster_id` in place.

### Terraform Version
1.4.2, shouldn't be related to version.

### Affected Resource(s)
- `openstack_containerinfra_nodegroup_v1`

### Terraform Configuration Files
```hcl
resource "openstack_containerinfra_nodegroup_v1" "static" {
  name         = each.value.name
  cluster_id   = local.cluster.id
  node_count   = 1

}
```
### Expected Behavior

Cluster gets replaced, therefore cluster will have a new id
After terraform recreated the cluster, it tries to update the nodegroup with the new ID of the parent cluster. This won't work, as you cannot attach an existing nodegroup to a new cluster.

### Actual Behavior
Terraform detects the change of cluster ID and replaces the nodegroup with a new one.

### Steps to Reproduce
1. `terraform apply -replace "path.to.parent.cluster"`

### Possible Solution
I'm not too deep into the sourcecode, but I guess the `ForceNew` property of `cluster_id` must be set to true.

https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_containerinfra_nodegroup_v1.go#LL45C10-L45C10

**Comment by mnaser** [comment]
Indeed, you're right, if the `cluster_id` is to be changed, the node group should indeed disappear.
