### ISSUE TITLE
[Documentation] terraform import command arguments are not displayed in Terraform Registry documentation

### ISSUE THREAD

**Issue by vzabawski** [terraform-provider-openstack/terraform-provider-openstack#1543]
Lots of documentation pages for Openstack resources contain `terraform import` command with arguments like `<instance_id>` which are not properly displayed in Terraform Registry documentation.

[Markdown file](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/website/docs/r/compute_floatingip_associate_v2.html.markdown):
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/17778043/231770874-7e048b55-2cc9-4e98-8d8d-6ac2232ed7b0.png">

[Terraform registry](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_floatingip_associate_v2):
<img width="716" alt="image" src="https://user-images.githubusercontent.com/17778043/231770933-5150ab8d-bd5e-48d1-a349-78e582035b64.png">

As you can see, values inside `<>` are not displayed.

**Comment by nikParasyr** [comment]
@vzabawski thanks for reporting this. I'll update docs to fix this
