### ISSUE TITLE
cannot set mac for instance

### ISSUE THREAD

**Issue by unclesamwk** [terraform-provider-openstack/terraform-provider-openstack#1547]
Hey, 

cannot set macadress for an openstack_compute_instance_v2:

```
resource "openstack_compute_instance_v2" "js01" {
  name            = "js01.${var.ad_user}"
  image_id        = "b3309ab3-dca1-4a3e-b2ff-99040e748382"
  flavor_name     = "n1.xlarge"
  key_pair        = "${var.ad_user}"
  security_groups = [
    "default",
    "${var.ad_user}-js01"
  ]

  metadata = {
    this = "that"
  }

  network {
    name = "${var.ad_user}_js01"
    fixed_ip_v4 = "172.16.0.44"
    mac = "fa:16:3e:2f:1b:ab"
  }

  depends_on = [
   openstack_networking_network_v2.js01,
   openstack_networking_subnet_v2.subnet_1,
   openstack_compute_secgroup_v2.secgroup_js01
  ]

}
```

Error:
```
│ Error: Value for unconfigurable attribute
│ 
│   with openstack_compute_instance_v2.js01,
│   on servers.tf line 18, in resource "openstack_compute_instance_v2" "js01":
│   18:     mac = "fa:16:3e:2f:1b:ab"
│ 
│ Can't configure a value for "network.0.mac": its value will be decided automatically based on the result of applying this configuration.
╵
```

Anyone an idea?

Greetings
Sam

**Comment by nikParasyr** [comment]
AFAIK you cannot define the mac when using `network`. This is not allowed on Openstack API level ( i checked quickly but maybe i made a mistake).

If you want to define the mac yourself, you should create a port resource => https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/networking_port_v2

and then create a instance resource that uses that port => https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_instance_v2#port

Keep in mind, that when using port the security groups need to be set on the port resource and not the instance.

Hope this helps

**Comment by nikParasyr** [comment]
@unclesamwk did the above approach work?

**Comment by unclesamwk** [comment]
Hey,

yes it works for me. Thx.

Greetings
Sam
