### ISSUE TITLE
openstack_compute_keypair_v2 - public_key attribute does not seem to work with Terraform file command

### ISSUE THREAD

**Issue by JoshuaSBrown** [terraform-provider-openstack/terraform-provider-openstack#1555]
This looks like a bug to me.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v 1.4.5 
Using version 1.51.1

### Affected Resource(s)
- openstack_compute_keypair_v2

These were set like so:

```
resource "openstack_compute_keypair_v2" "key" {
  name       = var.ssh_key_name
  public_key = file("${var.ssh_key_file}")
}
```

### Expected Behavior
What should have happened?

Terraform allows you to read in the public key using the terraform file command.

### Actual Behavior
It looks like when file is used to read in the public key heredoc notation prevents it from being accepted. 

```
Error: Unable to create openstack_compute_keypair_v2 datafedci-orc-terraform: Bad request with: [POST https://orc-open.ornl.gov:13774/v2.1/os-keypairs], error message: {"badRequest": {"code": 400, "message": "Keypair data is invalid: failed to generate fingerprint"}}
```

The output from using the plan command gives, here you can see the addition of EOT:

```
 # openstack_compute_keypair_v2.key will be created
  + resource "openstack_compute_keypair_v2" "key" {
      + fingerprint = (known after apply)
      + id          = (known after apply)
      + name        = "my_awesome_public_key"
      + private_key = (known after apply)
      + public_key  = <<-EOT
            ssh-rsa
            blahblahblah
            some_comment
        EOT
      + region      = (known after apply)
      + user_id     = (known after apply)
    }
```

The problem goes away if instead of using file I pass in the public key directly as a string in the OpenStack resource.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

```main.tf
terraform {
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 1.51.0"
    }
  }

  backend "http" {
  }
}

provider "openstack" {
  # OS_APPLICATION_CREDENTIAL_ID
  application_credential_id   = var.ci_openstack_app_id
  # OS_APPLICATION_CREDENTIAL_NAME
  application_credential_name   = var.ci_openstack_app_name
  # OS_APPLICATION_CREDENTIAL_SECRET
  application_credential_secret   = var.ci_openstack_app_secret
  # Comes from the user id that is listed on the Open Stack UI and is associated with the application credential
  user_id = var.ci_openstack_user_id
  # OS_AUTH_URL
  auth_url    = var.ci_openstack_url
}

resource "openstack_compute_keypair_v2" "key" {
  name       = var.ssh_key_name
  public_key = file("${var.ssh_key_file}")
}
```

1. `terraform apply`

**Comment by kayrus** [comment]
@JoshuaSBrown it looks like you're trying to upload a public key that cannot be parsed by openstack API. it should be in `ssh-rsa AAAA... comment` format without newlines. Can you check this one more time?

**Comment by JoshuaSBrown** [comment]
Thanks for the suggestion, this issue was raised more than a year ago, you are probably right in your suggestion, I just don't have access to the code anymore.
