### ISSUE TITLE
Update in-place instead of replacement

### ISSUE THREAD

**Issue by tibeer** [terraform-provider-openstack/terraform-provider-openstack#1562]
Today I noticed that a change of the image of a compute_instance will not trigger a replacement any more.
Instead, a "update in-place" is triggered. This behaviour is sort of unexpected as it goes along with data loss and might mislead people to think that there is no data loss. 

### Terraform Version
```
tibeer@tibeer % terraform -v
Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.51.1

Your version of Terraform is out of date! The latest version
is 1.4.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

- openstack_compute_instance_v2

### Terraform Configuration Files

Too much modules, so I just pasted the output of the plan.

```hcl
(...)
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.mycloud[0].module.vm.openstack_compute_instance_v2.instance will be updated in-place
  ~ resource "openstack_compute_instance_v2" "instance" {
      ~ flavor_name         = "SCS-1L:1:5" -> "SCS-8V:32:100"
        id                  = "f210192e-fe21-4ff5-86ab-33a7d06223db"
      ~ image_name          = "CirrOS 0.6.1" -> "Ubuntu 22.04"
        name                = "instance-0"
        tags                = []
        # (14 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
(...)
```

### Debug Output

None

### Panic Output

None

### Expected Behavior

There should have been a replacement notification. OpenStack itself marks it as a re-creation.

### Actual Behavior

The actions are reported as "update in-place".

### Steps to Reproduce

1. Create an example VM
2. Change the image_name of the VM
3. Run `terraform plan`
4. See that there is no "replace/recreate" notification

### Important Factoids

None

### References

None

**Comment by kayrus** [comment]
@tibeer thanks for submitting a bug report.

For the flavors, TF OpenStack provider supports online resize. So this is an expected behavior.

As for the images, they also support an OpenStack Nova rebuild call, see [rebuild](https://docs.openstack.org/api-ref/compute/?expanded=rebuild-server-rebuild-action-detail#rebuild-server-rebuild-action)

If you want to recreate an instance on certain event you can use the [replace_triggered_by](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by) meta-argument.

**Comment by tibeer** [comment]
Thanks a lot. I was just confused because in older revisions, there was no rebuild triggered but instead a recreate. It kind of makes sense to have it just "changed" with rebuild, but it might confuse users of other clouds, too. If you replace an image name or id on another public cloud provider / hyperscaler, they will always be replaced. But I got it now clear for me, thanks :)
