### ISSUE TITLE
Helper func for setting microversions

### ISSUE THREAD

**Issue by nikParasyr** [terraform-provider-openstack/terraform-provider-openstack#1575]
On some resources we have to set different microversions depending on various features that are required. We currently do not have any checks that we don't overwrite a microversion set previously. We should introduce a helper func that ensures that we are not overwriting a previously set microversion.

Things to consider:
- typically setting the microversion as the highest required is suffiecient
- there are cases though, where some features are only available in a range of microversions, e.g 2.47 -> 2.55, so in that case if a different feature requires > 2.55 setting it to the highest will lead to error

**Comment by kayrus** [comment]
We already have some logic in https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/1d6c2a84c648ffe62aa52e4032da1c7c1d151371/openstack/util.go#L207-L209
