### ISSUE TITLE
[instance v2]: missing `block_device` config after importing

### ISSUE THREAD

**Issue by 0xmeyer** [terraform-provider-openstack/terraform-provider-openstack#1597]
Hi,

I want to import manually created instances into Terraform, but I noticed that not all configurations are imported. Currently the configuration for `block_devices` is missing in the Terraform state and therefore the instance should be recreated.

Is this behavior intended?

## Terraform Version

```bash
Terraform v1.5.2
on linux_amd64
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.52.1
```

## Affected Resource

- `openstack_compute_instance_v2`

## Expected Behavior

When importing existing instances into Terraform, all configurations should be imported so that the VM does not need to be recreated.

**Comment by nikParasyr** [comment]
Importing the `openstack_compute_instance_v2` resource has limitations. These are documented here: https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_instance_v2#importing-instances with some examples on how to overcome them if possible.

> Is this behavior intended?

Not really, but it is really hard to import the resource correctly for every use case as nova does not hold information that was passed during creation time.

This issue https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1280 also discusses this

**Comment by 0xmeyer** [comment]
ACK. ACK. I will find another solution for this problem. Editing the Terraform state manually might be one but I'm not sure.

Thank you!

**Comment by nikParasyr** [comment]
I'm closing this. The limitations are known and documented. We haven't found any way to overcome them (yet).
