### ISSUE TITLE
Creating a security group with argument tenant_id fails in terraform plan/apply

### ISSUE THREAD

**Issue by michaelbayr** [terraform-provider-openstack/terraform-provider-openstack#1602]
I want to create a security group on behalf of a different user in a different openstack project. I am running the terraform script as admin user. However it seems like creating a security group via terraform containing a "tenant_id" is not possible due to terraform not expecting the argument.

### Terraform Version
1.5.4

### Affected Resource(s)
- openstack_compute_secgroup_v2

### Terraform Configuration Files
```hcl
resource "openstack_compute_secgroup_v2" "HTTPS" {
  name        = "HTTPS"
  description = "Allow HTTPS access to instance from everywhere."
  tenant_id = openstack_identity_project_v3.PROJECTNAME.id
  rule {
    from_port   = 443
    to_port     = 443
    ip_protocol = "tcp"
    cidr        = "0.0.0.0/0"
  }
}
```

### Error Output
```
│ Error: Unsupported argument
│ 
│   on privateNetwork.tf line 61, in resource "openstack_compute_secgroup_v2" "HTTPS":
│   61:   tenant_id = openstack_identity_project_v3.PROJECTNAME.id
│ 
│ An argument named "tenant_id" is not expected here.
```

### Expected Behavior
The security group should be successfully created in the given project identified by 'tenant_id'.

### Actual Behavior
Terraform plan/apply fails because the argument 'tenant_id' is not expected in security group. However the [documentation](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/networking_secgroup_v2) says it is a possible argument. It also seems to be present in the corresponding [gophercloud](https://github.com/gophercloud/gophercloud/blob/2efc557a7a456081d7ef80fac0591da37c6296c2/openstack/networking/v2/extensions/security/groups/requests.go#L17) definition. 

### Steps to Reproduce
1. Add above security group to your terraform file.
1. `terraform plan`

### Important Factoids
We are running unmodified openstack 'zed'.

**Comment by mnaser** [comment]
You're looking at two different resources, you're using `openstack_compute_secgroup_v2` in your code but linking `openstack_networking_secgroup_v2` in the docs.

https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_secgroup_v2#argument-reference

This one does not have that indeed, you should switch to the networking one.  I'm closing this as it's invalid.

**Comment by michaelbayr** [comment]
Thank you for pointing out my mistake. I have no idea how I did not see that... Of course you are right and it works now. 
Sorry for the inconvenience. Have a nice day!
