### ISSUE TITLE
[Doc] openstack_compute_instance_v2 mentions deprecated resources

### ISSUE THREAD

**Issue by yomovh** [terraform-provider-openstack/terraform-provider-openstack#1604]
in [openstack_compute_instance_v2](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_instance_v2) the documentation mentions  associated ressources which are deprecated notably :
 openstack_blockstorage_volume_v2 & openstack_blockstorage_volume_v1 which are superseeded by openstack_blockstorage_volume_v3 

This has lead to some confusion for some users (see https://github.com/ovh/terraform-provider-ovh/issues/453)

Can you please confirm that this is not expected ? I can update the documentation if needed.

Thanks

**Comment by nikParasyr** [comment]
@yomovh 

You are right, this is not expected. The documention will be updated with the related PR, to only reference `openstack_blockstorage_volume_v3`.

thanks for reporting this.
