### ISSUE TITLE
Possibility to set tls on loadbalancer pools

### ISSUE THREAD

**Issue by tomasbackman** [terraform-provider-openstack/terraform-provider-openstack#1611]
## Problem

The openstack loadbalance pools have a settings for 
TLS enabled
TLS Cipher

But I can not find any way to set these through the terraform code. So I have resorted to bash scripts running openstack cli commands ... which does not feel good.

### Versions
Terraform: 1.5.5 (will not go above - openTF)
Openstack provider: 1.51.1

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_lb_pool_v2

### References
Other older GitHub issues that mentions this:
- GH-953

**Comment by kayrus** [comment]
@tomasbackman thank you for a bug report. Do you have pool members which serve traffic using TLS?

> So I have resorted to bash scripts running openstack cli commands ... which does not feel good.

could you please share the CLI commands you used?

**Comment by tomasbackman** [comment]
Thank you for prompt response, I unfortunately cannot do the same and will come back with more details next week

**Comment by kayrus** [comment]
> will come back with more details next week

@tomasbackman have you managed to get more details on this issue?
