### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by okozachenko1203** [terraform-provider-openstack/terraform-provider-openstack#1617]
Would it be possible to release a new version since the provider has a few improvements and fixes so far?
We received some requests from users to land this fix https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1598 for rolling updates.

**Comment by mnaser** [comment]
@nikParasyr not sure if I have the right tools to do this, but I'm happy to help arrange a release.

**Comment by nikParasyr** [comment]
Indeed it is a bit delayed. I’ll make one tomorrow or the day after
(@mnaser ill ping you the process, so you are aware)

**Comment by nikParasyr** [comment]
[v1.53.0](https://github.com/terraform-provider-openstack/terraform-provider-openstack/releases/tag/v1.53.0) has been released.
