### ISSUE TITLE
terraform init (with modules) not working

### ISSUE THREAD

**Issue by atfops** [terraform-provider-openstack/terraform-provider-openstack#1620]
Hi, 

I'm opening an issue, because I don't understand where is the issue of this initialization terraform env.

### Terraform Version
<img width="204" alt="Capture d’écran 2023-10-26 à 09 58 50" src="https://github.com/terraform-provider-openstack/terraform-provider-openstack/assets/120210590/5815b5da-43eb-4677-885d-ce7a6df47870">

### Debug Output
<img width="1440" alt="Capture d’écran 2023-10-26 à 09 57 44" src="https://github.com/terraform-provider-openstack/terraform-provider-openstack/assets/120210590/a1dd8ac2-c705-4e9c-a64f-00aff3df6dc6">

### Expected Behavior
terraform init gone validate.
Here is by adding an "terraform provider block" into my modules/web-app/main.tf code.
<img width="799" alt="Capture d’écran 2023-10-26 à 10 00 09" src="https://github.com/terraform-provider-openstack/terraform-provider-openstack/assets/120210590/12160eb3-d8cc-4f15-88b0-5450e0636021">

### Actual Behavior
It's actually looking for an hashicorp/openstack provider for my modules/web-app/main.tf module.
<img width="880" alt="Capture d’écran 2023-10-26 à 10 01 01" src="https://github.com/terraform-provider-openstack/terraform-provider-openstack/assets/120210590/485601bc-f555-4945-89c4-67c3dbb6dc94">

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create an `provider.tf`, `main.tf`and `modules/web-app/main.tf` terraform code structure
2. `terraform init`

provider.tf 
```
terraform {
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 1.51.1"
    }
  }
}

provider "openstack" {
  user_name   = var.os_user_name
  password    = var.os_password
  tenant_name = var.os_tenant
  tenant_id   = var.os_tenant_id
  auth_url    = var.os_auth_url

  domain_name         = var.os_domain_name
  project_domain_name = var.os_project_domain_name

  insecure = true
}
```

main.tf 
```
module "web-app" {
  source         = "./modules/web-app"
  prefix         = var.prefix
  os_region      = var.os_region
  flavor         = var.flavor
  uuid           = var.uuid
  volume_size    = var.volume_size
  public_network = var.public_network
  ssh_username   = var.ssh_username
}
```

modules/web-app/main.tf
```
variable "prefix" {}
variable "os_region" {}
variable "flavor" {}
variable "uuid" {}
variable "volume_size" {}
variable "public_network" {}
variable "ssh_username" {}

// docker instance
resource "openstack_compute_instance_v2" "pfewc-web-app" {
  name            = "${var.prefix}web-app"
  region          = var.os_region
  flavor_name     = var.flavor
  key_pair        = openstack_compute_keypair_v2.pfewc-key

}
```

### References
Find an issue in 2021 where somebody at Terraform spoke about that :
- https://github.com/hashicorp/terraform/issues/28407#issuecomment-821140569

**Comment by theolurat** [comment]
Yes that was surprising.. but still working by adding the provider block in each modules (even it's not really optimize)

**Comment by kayrus** [comment]
I'm closing this issue since it doesn't relate to this provider.
