### ISSUE TITLE
Report a bug with Terraform OpenStack Provider

### ISSUE THREAD

**Issue by AichaDevOps** [terraform-provider-openstack/terraform-provider-openstack#1621]
Hello, 

I encountered an error while using the Terraform OpenStack provider, specifically related to the openstack_compute_floatingip_associate_v2 resource.
When applying changes to the openstack_compute_floatingip_associate_v2 resource, I receive the following error message:

**Error: Provider produced inconsistent result after apply
When applying changes to openstack_compute_floatingip_associate_v2.rancher_workers_ips_attach[0], provider
"provider[\"registry.terraform.io/terraform-provider-openstack/openstack\"]" produced an unexpected new value: Root object was present, but now absent.
This is a bug in the provider, which should be reported in the provider's own issue tracker.**

Thank you for your assistance in resolving this matter.

**Comment by nikParasyr** [comment]
@AichaDevOps thanks for reporting this. Could you provide the following:
- a snippet of the code that fails
- the logs of the run (`TF_LOG=debug OS_DEBUG=1 terraform apply`)

**Comment by kayrus** [comment]
@AichaDevOps consider using the `openstack_networking_floatingip_associate_v2` resource. The `openstack_compute_floatingip_associate_v2` has been deprecated.

See an example here https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1711#issuecomment-2228072699
