### ISSUE TITLE
Support for 'compressed' container_format (Reference: https://github.com/openstack/glance/blob/stable/train/doc/source/user/formats.rst)

### ISSUE THREAD

**Issue by ramukima** [terraform-provider-openstack/terraform-provider-openstack#1633]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see https://www.terraform.io/community.html.

### Terraform Version
N/A

### Affected Resource(s)
Please list the resources as a list, for example:
- image_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Request to accept container_format as 'compressed', the current image_v2 validation does not include this new format.

### Actual Behavior
Request to accept container_format as 'compressed', per the latest train release of openstack.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Request to support 'compressed' container_format

### References
](https://github.com/openstack/glance/blob/stable/train/doc/source/user/formats.rst)

**Comment by ramukima** [comment]
As per the documentation here https://github.com/openstack/glance/blob/stable/train/doc/source/user/formats.rst, a container_format value 'compressed' is supported as part of latest stable openstack release. This ticker is an enhancement request to allow 'compressed' value for container_format in the validations for image_v2 resource.

**Comment by kayrus** [comment]
Relates to #1482

Are you willing to submit a PR for this feature? If yes, you need to be very careful and consider cases, when `decompress` is set to true.
