### ISSUE TITLE
Remove support for neutron lbaas in favor of Octavia

### ISSUE THREAD

**Issue by nikParasyr** [terraform-provider-openstack/terraform-provider-openstack#1638]
Currently most lbaas data-sources/resources work for both _neutron lbaas_ AND _octavia_. This leads to:
- the code being more complicated "than it should"
- new features from octavia cannot be introduced easily and quickly

Neutron lbaas has been deprecated since Queens(2018-02-28) and removed in Train(2019-10-16). 
We also dont have ci coverage for it for 2+ years.

The provider aims to support [all versions](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs#openstack-releases-and-versions) of Openstack and it doesn't have an official deprecation policy. That being said, since it is blocking us from adding new features AND it has been removed for 4 years, I am in favor of removing support for neutron lbaas from the provider.

Would like to hear more opinions on this and if anyone is still using neutron lbaas.

---

Update 29/01: New release was made with deprecation warning for all lbaas resources. Will start working on removing support for neutron lbaas and prep 2.0.0

Resources needing update:
- [x] l7 policy
- [x] l7 rule
- [x] listener
- [x] loadbalancer
- [x] members
- [x] member
- [x] monitor
- [x] pool
- [x] quota
- [x] various help functions, ci scripts and provider "use-octavia" attribute

**Comment by yomovh** [comment]
I agree that the provider shall fully support Octavia. If that means breaking some features from `neutron lbaas` then I can live with that.

**Comment by nikParasyr** [comment]
new release: https://github.com/terraform-provider-openstack/terraform-provider-openstack/releases/tag/v1.54.0 has marked the various resources as deprecated with a relevant message. Will slowly work into updating each resource
