### ISSUE TITLE
Deprecation warning triggered even when option use_octavia is not used nor set

### ISSUE THREAD

**Issue by cmd-ntrf** [terraform-provider-openstack/terraform-provider-openstack#1664]
### Terraform Version
```
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.54.0
```

### Affected Resource(s)

The warning is displayed when the provider is included, regardless of what resource is used.

### Terraform Configuration Files
```hcl
terraform {
required_version = ">= 0.14.0"
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 1.54.0"
    }
  }
}

provider "openstack" {}

data "openstack_compute_flavor_v2" "small" {
  vcpus = 1
  ram   = 512
}
```

### Expected Behavior

No deprecation warning

### Actual Behavior
```
╷
│ Warning: Argument is deprecated
│
│   with provider["registry.terraform.io/terraform-provider-openstack/openstack"],
│   on test.tf line 11, in provider "openstack":
│   11: provider "openstack" {}
│
│ This option will be removed in the next major release. Support for neutron-lbaas will be removed in next major release. Octavia will
│ be the only option supported.
╵
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### References
- Problem was introduced by https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1640

**Comment by nikParasyr** [comment]
@cmd-ntrf 

This warning is for the `use_octavia` config on the provider block. 
I understand this might be annoying, especially for people not using octavia or neutron-lbaas, but the warning will stay till the 2.0.0 release

**Comment by cmd-ntrf** [comment]
If it has to stay, I would recommend to improve the warning by making it clear it can be ignored if not used. I had to dig in my provider declaration, then read the actual go code of the provider to be certain I had nothing to do.

**Comment by nikParasyr** [comment]
@cmd-ntrf indeed the message is not clear. I thought (wrongly and i should have doublechecked) that the message would be shown only to people which use the `use_octavia` argument. This is not the case. 
The message was not clear in general, so I made a small change and i will roll out a patch release for it (1.54.1).

Sorry for noise and un-clarity. Hopefully the new message is a bit clearer.
Ill focus on 2.0.0 to get the message removed completely :)
