### ISSUE TITLE
New resources for BGP VPN

### ISSUE THREAD

**Issue by donyo-donev** [terraform-provider-openstack/terraform-provider-openstack#1666]
Hello,  

We would like to ask if there are any plans to implement BGP VPN Terraform resources? If so, could you also provide the expected timeline for its introduction?

### Affected Resource(s)
Proposal for new resource name: openstack_networking_bgpvpn_v2

### Expected Behavior
We would like to create BGP VPN in OpenStack and make association of routers via Terraform.

### Actual Behavior
Up to now it is possible to create BGP VPN via OpenStack CLI.

### Steps to Reproduce
There are no steps, because this is a new feature request. 

Thank you in advance!

**Comment by kayrus** [comment]
depends on https://github.com/gophercloud/gophercloud/issues/2209
