### ISSUE TITLE
Documentation: floatingIP datasource uses pool ID, not name

### ISSUE THREAD

**Issue by GoodOldJack12** [terraform-provider-openstack/terraform-provider-openstack#1690]
### Terraform Version
Terraform v1.7.4-dev

### Affected Resource(s)
openstack_networking_floatingip_v2

### Terraform Configuration Files
```
data "openstack_networking_floatingip_v2" "public" {
  pool = "myPool"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
The floating IP is found based on the name of the pool.

### Actual Behavior
The floating IP was not found. It was only found when given the _id_ of the pool. 

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/data-sources/networking_floatingip_v2#pool

**Comment by nikParasyr** [comment]
Hello. This has been addressed in https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1678 but it is not released yet
