### ISSUE TITLE
I can't define "fixed_ip" parameter for openstack_networking_port_v2 using a list based on splat syntax list of subnets IDs

### ISSUE THREAD

**Issue by anta5010** [terraform-provider-openstack/terraform-provider-openstack#170]
### Terraform Version
$ terraform -v
Terraform v0.11.0
+ provider.null v1.0.0
+ provider.openstack v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)
openstack_networking_port_v2 but it might be a common issue for other openstack provider resources

### Terraform Configuration Files

I would like to define fixed IPs dynamically for openstack_networking_port_v2 definitions using splat syntax list of subnets IDs. This way I can deploy IPv4-only  or IPv4+IPv6 networks using the same terraform definitions.

```hcl

variable "is_ipv6" {}

resource "openstack_networking_subnet_v2" "s1_public" {
  count      = "${var.is_ipv6+1}"
  name       = "${var.cdn_name}s1.public_v${count.index == 0 ? 4 : 6}-${var.user_name}"
  network_id = "${openstack_networking_network_v2.s1_public.id}"
  cidr       = "${element(var.cdn_ipnets["s1_public"], count.index)}"
  ip_version = "${ count.index == 0 ? 4 : 6 }"
}

data "null_data_source" "s1_public_gw_ips" {
  count = "${var.is_ipv6+1}"
  depends_on = [ "openstack_networking_subnet_v2.s1_public" ]
  inputs = {
    subnet_id = "${element(openstack_networking_subnet_v2.s1_public.*.id,count.index)}"
    ip_address = "${cidrhost(element(var.cdn_ipnets["s1_public"], count.index), var.public_offsets["gw1"])}"
  }
}

resource "openstack_networking_port_v2" "rtr_s1_public_port" {
  name = "gw1.${var.cdn_name}s1.public-${var.user_name}"
  network_id = "${openstack_networking_network_v2.s1_public.id}"
  admin_state_up = "true"
  depends_on = [ "data.null_data_source.s1_public_gw_ips" ]

  fixed_ip = [ "${data.null_data_source.s1_public_gw_ips.*.inputs}" ]
}
```

### Expected Behavior

  A port should be created with either one (ipv4) or two (ipv4 and ipv6) IP addresses depending on is_ipv6 variable.

### Actual Behavior
```
Error: openstack_networking_port_v2.rtr_s1_public_port: "fixed_ip.0.subnet_id": required field is not set
```

### Steps to Reproduce

"terrform plan" or "terraform apply"

### Important Factoids

And after applying my definition to an openstack (with fixed_ip definition commented out of course) I can check with "terraform console" that my null_data_source is defined correctly:

```
> data.null_data_source.s1_public_gw_ips.*.inputs
[
  {    ip_address = 172.25.123.1  subnet_id = cab2bffa-d0f0-42fa-bc06-6e03f9a8dd67},
  {    ip_address = 2a00:81c0:6001:141::1  subnet_id = 455444dc-7211-4a6a-a610-9fe480ff9ebc}
]
> keys(data.null_data_source.s1_public_gw_ips.*.inputs[0])
[
  ip_address,
  subnet_id
]
> lookup(data.null_data_source.s1_public_gw_ips.*.inputs[0], "subnet_id")
cab2bffa-d0f0-42fa-bc06-6e03f9a8dd67
```

I tried with and without all the dependencies listed explicitly.
I think there is something wrong with parsing fixed_ip value if it's based on a splat syntax list. For testing purposes I also tried to use Local values with the same result. For example:

``` hcl
locals {
  s1_public_gw_ips = [
        {
          "ip_address" = "${cidrhost(element(var.cdn_ipnets["s1_public"], 0), var.public_offsets["gw1"])}"
          "subnet_id" = "${element(openstack_networking_subnet_v2.s1_public.*.id,0)}"
        },
        {
          "ip_address" = "${cidrhost(element(var.cdn_ipnets["s1_public"], 1), var.public_offsets["gw1"])}"
          "subnet_id" = "${element(openstack_networking_subnet_v2.s1_public.*.id,1)}"
        },
  ]
}

resource "openstack_networking_port_v2" "rtr_s1_public_port" {
  name = "${lookup(local.s1_public_gw_ips[0], "subnet_id")}"
  network_id = "${openstack_networking_network_v2.s1_public.id}"
  admin_state_up = "true"

  fixed_ip = [ "${local.s1_public_gw_ips}" ]
}
```

In the example above I even defined "name" using the same local variable list and it works fine. So, the issue not with the list in local variables and not with the list from null_data_source, but with parsing the fixed_ip parameter.

**Comment by fatmcgav** [comment]
As per my comment on #174, this feels like more of a Terraform HCL issue than a provider issue... 

I'll reach out to Hashicorp and see if I can get some feedback...

**Comment by jtopjian** [comment]
Similar to #174, `fixed_ip` is not a list per-se. It's a list of repeatable schema items ("block"). Because of this, you can't assign an arbitrary list/map and circumvent the fields.

Again, making a `openstack_networking_port_fixed_ip_v2` resource might be the best long-term solution.

**Comment by gaui** [comment]
This is a bug in Terraform core. Related: https://github.com/terraform-providers/terraform-provider-null/issues/18
