### ISSUE TITLE
Instance does not output its port ID

### ISSUE THREAD

**Issue by framctr** [terraform-provider-openstack/terraform-provider-openstack#1711]
### Terraform Version
Terraform v1.7.2

### Affected Resource(s)
- openstack_compute_instance_v2

### Terraform Configuration Files
```hcl
resource "openstack_compute_instance_v2" "example" {
  ...
  network {
    name = var.network_name
  }
}

output "debug" {
  value = openstack_compute_instance_v2.example.network.port
}
```

### Expected Behavior
The output should show the port ID of the instance

### Actual Behavior
No output (port value is `null`).

**Comment by srieger1** [comment]
This is especially problematic, as `openstack_compute_floatingip_associate_v2` is deprecated, but `openstack_networking_floatingip_associate_v2` only works with a port ID. I also tried to query the port ID using a separate data source query after the instance is created, but the string for the port ID of my test instance `openstack_compute_instance_v2.terraform-instance-1.network[0].port` stays "".

**Comment by nikParasyr** [comment]
i had a quick check and this doesnt seem to be an easy fix.

to the extend that it is possible i would recommend to have a separate port resource and use that on the instance resource. This should alleviate the above issue. So:

```
resource "openstack_networking_network_v2" "network_1" {
  name           = "network_1"
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "subnet_1" {
  name       = "subnet_1"
  network_id = openstack_networking_network_v2.network_1.id
  cidr       = "192.168.199.0/24"
}

resource "openstack_networking_port_v2" "port_1" {
  name           = "port_1"
  network_id     = openstack_networking_network_v2.network_1.id
  admin_state_up = "true"
  security_groups = ["default"]

  fixed_ip {
    subnet_id = openstack_networking_subnet_v2.subnet_1.id
  }
}

resource "openstack_compute_instance_v2" "basic" {
  name            = "basic"
  image_id        = "ad091b52-742f-469e-8f3c-fd81cadf0743"
  flavor_id       = "3"
  key_  security_groups = ["default"]pair        = "my_key_pair_name"

  network {
    port = openstack_networking_port_v2.port_1.id
  }
}
```

**Comment by framctr** [comment]
Yes, I was already doing it in the way @nikParasyr suggested.

At this point, I was thinking if it would be easier and more maintenable to detach the network block from the instance resource, leaving only a `port_ids` input for the resource, and force users using the `openstack_networking_port` resource. This will maybe simplify code and keep things working. The only issue I see is that the `port` resource does not accept `network_name` as input, but only `network_id`, while the instance accepts both. For example, I give unique names to my networks and I have modules accepting a network name as an input variable.

**Comment by framctr** [comment]
I would also say that the deprecation of the `openstack_compute_floatingip_associate_v2` resource creates a bit of confusion on users because there is no documentation on how to replace it with the networking resources

**Comment by kayrus** [comment]
> I would also say that the deprecation of the `openstack_compute_floatingip_associate_v2` resource creates a bit of confusion on users because there is no documentation on how to replace it with the networking resources

we'll try to fix this within #1741

**Comment by kayrus** [comment]
There is a solution to move from the `openstack_compute_floatingip_associate_v2` to the `openstack_networking_floatingip_associate_v2`:

```hcl
resource "openstack_compute_instance_v2" "vm_1" {
  name = "terraform-test-vm"

  security_groups = [
    data.openstack_networking_secgroup_v2.default.name,
  ]

  flavor_id = data.openstack_compute_flavor_v2.vm_flavor_1.id
  key_pair  = data.openstack_compute_keypair_v2.keypair.name
  image_id  = data.openstack_images_image_v2.image.id

  network {
    uuid = data.openstack_networking_network_v2.network.id
  }
}

data "openstack_networking_port_v2" "vm_port_1" {
  device_id = openstack_compute_instance_v2.vm_1.id
}

resource "openstack_networking_floatingip_associate_v2" "fip_associate" {
  floating_ip = openstack_networking_floatingip_v2.fip_vm.address
  port_id     = data.openstack_networking_port_v2.vm_port_1.id
}
```

**Comment by kayrus** [comment]
the `openstack_networking_port_v2`  data source should be enough to cover the use case
