### ISSUE TITLE
dns-publish-fixed-ips flag in openstack_networking_subnet_v2

### ISSUE THREAD

**Issue by p-cyr** [terraform-provider-openstack/terraform-provider-openstack#1730]
We are currently running Openstack with Designate that automatically generates private records. To enable this, the 'dns-publish-fixed-ips' needs to be set. 
#
The latest version of the 'openstack_networking_subnet_v2' does not implement this flag yet. 

### Expected Behavior
Have a new flag implemented 

resource "openstack_networking_subnet_v2" "subnet" {
  network_id      = openstack_networking_network_v2.network.id
  name            = "network-subnet"
  cidr            = '10.0.0.0/24'
  dns_nameservers = '10.0.0.10'
  dns-publish-fixed-ips = true
}

### Actual Behavior
│ Error: Unsupported argument
│
│   on .\resources.tf line 11, in resource "openstack_networking_subnet_v2" "subnet":
│   11:   dns-publish-fixed-ips = true
│
│ An argument named "dns-publish-fixed-ips" is not expected here.
╵

### Steps to Reproduce
`terraform apply`

### References
Terraform network_subnet_v2 documentation : [https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/networking_subnet_v2](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/networking_subnet_v2)
Openstack subnet documentation : [https://docs.openstack.org/python-openstackclient/latest/cli/command-objects/subnet.html](https://docs.openstack.org/python-openstackclient/latest/cli/command-objects/subnet.html)

**Comment by pabclsn** [comment]
same really needed here ;)

**Comment by kayrus** [comment]
you can use `value_specs` argument https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/networking_subnet_v2#value_specs
example:
```hcl
resource "openstack_networking_network_v2" "network_1" {
  name           = "tf_test_network"
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "subnet_1" {
  network_id = openstack_networking_network_v2.network_1.id
  cidr       = "192.168.199.0/24"
  value_specs = {
    dns_publish_fixed_ip = true
  }
}
```

**Comment by kayrus** [comment]
Looks like `value_specs.dns_publish_fixed_ip = true` sends `"true"` in JSON requests. If this hack doesn't work, try with the #1743

**Comment by kayrus** [comment]
The #1743 is a quick hack, which can help on on creation stage. The actual fix should be in the gophercloud.
I see a corresponding PR in https://github.com/gophercloud/gophercloud/pull/3090
Once it's merged, it should be backported to v1, since we're not yet ready to migrate to v2.
