### ISSUE TITLE
allowed_address_pairs does not accept list

### ISSUE THREAD

**Issue by michalmedvecky** [terraform-provider-openstack/terraform-provider-openstack#174]
`allowed_address_pairs` does not accept (correct?) interpolated parameter.

### Terraform Version

0.11

### Affected Resource(s)
- openstack_networking_port_v2

### Terraform Configuration Files

First declare 10 ports:

```hcl
resource "openstack_networking_port_v2" "vip" {
  name = "mytest-${count.index}"
  network_id = "${openstack_networking_network_v2.net-backend.id}"
  admin_state_up = "true"
  count = "10"
}
```

Next, create port where those 10 addresses are allowed:

```hcl
resource "openstack_networking_port_v2" "port" {
  name = "mytest"
  admin_state_up = "true"
  network_id = "${openstack_networking_network_v2.net-backend.id}"
  allowed_address_pairs = "${formatlist("{ip_address=\"%v\"}", 
  openstack_networking_port_v2.vip.*.all_fixed_ips.0)}"
}
```

### Actual result

```
Error: openstack_networking_port_v2.port: allowed_address_pairs: should be a list
```

If you output the interpolation:

```hcl
output "mylist" {
  value="${formatlist("{ ip_address=\"%v\" }", openstack_networking_port_v2.vip.*.all_fixed_ips.0)}"
}
```

you get:

```
mylist = [
    { ip_address="100.127.172.186" },
    { ip_address="100.127.172.19" },
    { ip_address="100.127.172.180" },
    { ip_address="100.127.172.18" },
    { ip_address="100.127.172.182" },
    { ip_address="100.127.172.184" },
    { ip_address="100.127.172.189" },
    { ip_address="100.127.172.183" },
    { ip_address="100.127.172.179" },
    { ip_address="100.127.172.181" }
]
```

And if you copypaste this output to the `.tf` file, it works. But that's not what you want to do :-)

**Comment by anta5010** [comment]
Firstly, try to put square brackets:

```
allowed_address_pairs = [ "${formatlist("{ip_address=\"%v\"}", openstack_networking_port_v2.vip.*.all_fixed_ips.0)}" ]

```

If this doesn't work then I think this issue has the same root cause as the one I raised
https://github.com/terraform-providers/terraform-provider-openstack/issues/170

**Comment by michalmedvecky** [comment]
I tried. The difference is `Error: openstack_networking_port_v2.ldap16_port: "allowed_address_pairs.0.ip_address": required field is not set`

**Comment by anta5010** [comment]
Then it's exactly the issue I mentioned in https://github.com/terraform-providers/terraform-provider-openstack/issues/170 but in a different place

**Comment by michalmedvecky** [comment]
So hopefully Hashiguys will have a look soon 🙏

**Comment by fatmcgav** [comment]
On the surface this feels more like a Terraform HCL issue than an Openstack provider issue... 

I'll reach out and see if I can get some feedback... :)

**Comment by jtopjian** [comment]
@michalmedvecky Has this worked in a previous version of Terraform?

`allowed_address_pairs` isn't a list - it's a block which has `ip_address` as a sub-argument. It's expecting something like:

```hcl
allowed_address_pairs {
  ip_address = ip1
}

allowed_address_pairs {
  ip_address = ip2
}

allowed_address_pairs {
  ip_address = ip3
}

allowed_address_pairs {
  ip_address = ip4
}
```

**Comment by michalmedvecky** [comment]
I never tried before - I don't know.

Did you know that

```hcl
allowed_address_pairs = [
  { ip_address = "1.2.3.4"},
  { ip_address = "2.3.4.5"}
]

works as expected?

What should I do to reach my goal - to automate passing IPs to `allowed_address_pairs`?

**Comment by michalmedvecky** [comment]
@jtopjian if you say _isn't a list_ then what the message means? `Error: openstack_networking_port_v2.port: allowed_address_pairs: should be a list` 

Don't tell me we're going to resolve this issue by modifying the error message :D

**Comment by jtopjian** [comment]
> Did you know that works as expected?

Ah, OK. So if it works when you have the value set statically, then the resource supports that kind of formatted value. This is news to me - I wouldn't have thought Terraform would allow that from the start.

I agree with @fatmcgav here - we're going to reach out to core for some help.

One possible solution for this is to break `allowed_address_pairs` into a dedicated resource. That's been the solution in the past when this kind of resource relationship is needed.

**Comment by jtopjian** [comment]
>  if you say isn't a list then what the message means?

Well, it _is_ a list. However, it is a list of "schema" items :) Very much different than, say, a list of strings. So I think we can narrow down the issue to "can interpolation work when providing a value to a list/set of schema items"

**Comment by michalmedvecky** [comment]
So any workaround suggestion until feedback from core? I have no idea how to "break allowed_address_pairs into a dedicated resource"

**Comment by jtopjian** [comment]
> I have no idea how to "break allowed_address_pairs into a dedicated resource"

That's something on the development side.

**Comment by anta5010** [comment]
> So I think we can narrow down the issue to "can interpolation work when providing a value to a list/set of schema items"

@jtopjian This is what I meant by "a list based on splat syntax" in https://github.com/terraform-providers/terraform-provider-openstack/issues/170

**Comment by anta5010** [comment]
> So any workaround suggestion until feedback from core? 

  What you  can do is: create a separate module with a "null_data_source" as I do in  https://github.com/terraform-providers/terraform-provider-openstack/issues/170 and set output of this module as the "null_data_source" inputs. Then in your module you can set allowed_address_pairs to that module output. This way it works.

**Comment by jtopjian** [comment]
We've got confirmation that this isn't supported. It works when you hard-code the values:

```hcl
allowed_address_pairs = [
  { ip_address = "1.2.3.4"},
  { ip_address = "2.3.4.5"}
]
```

But that's a side-effect / coincidence. Not a supported feature.

This method of using HCL might be supported in the future. For now, a dedicated `openstack_networking_allowed_address_pair_v2` resource is probably the best "proper" solution. If workarounds work (such as what @anta5010 described) you're more than welcome to continue using them.

**Comment by jtopjian** [comment]
Just wanted to touch base on this. I've looked into a dedicated resource and I'm not sure if that will even fix this. I'm going to keep looking into solutions, though it's quite possible this might be a limitation of HCL for the time being.

**Comment by anta5010** [comment]
@jtopjian I don't know if it would help you but the "network" parameter for the "openstack_compute_instance_v2" resource accepts splat syntax lists. For example, this works fine:

```
data "null_data_source" "uplink_networks" {
  count  = "${local.uplink_count}"
  inputs = {
    port = "${element(openstack_networking_port_v2.uplink_port.*.id, count.index)}"
  }
}

data "null_data_source" "networks" {
  count  = "${local.interface_count}"
  inputs = {
    port = "${element(openstack_networking_port_v2.port.*.id, count.index)}"
  }
}

resource "openstack_compute_instance_v2" "instance" {
  name            = "${var.name}"
  image_name      = "${var.image_name}"
  flavor_name     = "${var.flavor_name}"
  key_pair        = "${var.key_pair}"

  user_data       = "${var.user_data}"

  network         = ["${concat(data.null_data_source.uplink_networks.*.inputs, data.null_data_source.networks.*.inputs)}"]
}

```

So, only some parameters are limited.

**Comment by michalmedvecky** [comment]
Any chance to move on with this? I'm really pissed off by workarounding this 🙄

**Comment by gaui** [comment]
This is a real blocker for us. Related: https://github.com/terraform-providers/terraform-provider-null/issues/18

**Comment by splashx** [comment]
@michalmedvecky you should use the new syntax:

```hcl
locals {
  some_list_of_ips = [
    "127.0.0.1",
    "127.0.0.2",
    "127.0.0.3"
  ]
}

resource "openstack_networking_port_v2" "test-adp" {
  name           = "some-name"
  count          = "1"
  network_id     = "ef3a3380-931e-45fc-a7b8-6a1ad3bc24ab"
  admin_state_up = "true"
  dynamic "allowed_address_pairs" {
    for_each = local.some_list_of_ips
    content {
      ip_address = allowed_address_pairs.value
    }
  }
}
```


```shell
$ openstack port show some-name --format=json | jq '.allowed_address_pairs'
"ip_address='127.0.0.1', mac_address=''\nip_address='127.0.0.2', mac_address=''\nip_address='127.0.0.3', mac_address=''"
```

Of course one can use a list of IPs in splat syntax instead of `some_list_of_ips`.

This issue should be closed.

**Comment by michalmedvecky** [comment]
@splashx I don't need this anymore. I can ask my then-employer to use HCL2 ...

**Comment by styk-tv** [comment]
@splashx I thank you!
