### ISSUE TITLE
compute floatingips

### ISSUE THREAD

**Issue by pierreprinetti** [terraform-provider-openstack/terraform-provider-openstack#1741]
I am building a [migration script](https://github.com/gophercloud/gophercloud/pull/3085) for adapting codebases to Gophercloud v2.

In that context, I am wondering what to do with `compute/v2/extensions/floatingips`. That functionality is offered by Neutron at this point, and has been for quite a while. However, in `terraform-provider-openstack` `resourceComputeFloatingIPV2` and `resourceNetworkingFloatingIPV2` have a different API, and more specifically the legacy Compute version has the parameter `instance_id` that is not available in the Networking replacement.

So my question is: going forward, what do you want to do with `resourceComputeFloatingIPV2`, in the context of an upgrade to Gophercloud v2, which doesn't offer `floatingips` under `compute` any more?

**Comment by kayrus** [comment]
According to docs, this resource is deprecated: https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_floatingip_v2
Therefore we can easily remove this code.

**Comment by pierreprinetti** [comment]
Is that something you're willing to do? I don't want angry users coming at ME for removing the resource :joy:

**Comment by kayrus** [comment]
@pierreprinetti I'll manage this.

**Comment by kayrus** [comment]
@nikParasyr when do we plan to remove deprecated resources?

**Comment by nikParasyr** [comment]
@kayrus  see my remark [here](https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1751#pullrequestreview-2184881976)
