### ISSUE TITLE
[Feature] Add an option when destroying a project to cleanup all resources in this project

### ISSUE THREAD

**Issue by dparv** [terraform-provider-openstack/terraform-provider-openstack#1774]
Currently if you create a project with terraform and create additional resources in that project, that terraform doesn't manage - running destroy will destroy the project, but leave those un-managed resources.

I would like to have an option that will run the equivalent of `openstack project purge --project UUID` when the provider does the destroying. A boolean should suffice, e.g.:

```
  resource "openstack_identity_project_v3" "project" {                                                                    
    name        = "my-project-name"
    description = "A project for Terraform"
    purge_project_on_destroy = true
  }                                                                                                                       
```

**Comment by kayrus** [comment]
This is impossible. OpenStack project can contain a set of custom developed services. For example Huawei Cloud is an OpenStack cloud with additional services, e.g. https://www.huaweicloud.com/intl/en-us/product/vpcep.html. And there are many other OpenStack based clouds, which have their own set of services.
We cannot track everything and handle each service.
