### ISSUE TITLE
Authentication via Token not possible

### ISSUE THREAD

**Issue by hurdigurdi** [terraform-provider-openstack/terraform-provider-openstack#231]
Hi there,

using terraform version 0.11.3 with provider-openstack 1.2 against a custom openstack implemenation.

When using username/password, authentication works fine for both local and remote (swift) statefiles.

By using a working configuration and just replacing username/password by a valid authentication token, the following is perceived:
`terraform init -backend-config 'auth_url=https://identity.eu-de-1.auth.server:443/v3' -backend-config 'tenant_name=ProjectName' -backend-config 'domain_name=mydomain' -backend-config 'token=gAAAAA...' -backend-config 'region_name=eu-de-1'

Initializing the backend...

Error configuring the backend "swift": DomainName may not be provided when authenticating with a TokenID`

removing the domain-name from configuration:
`terraform init -backend-config 'auth_url=https://identity.eu-de-1.auth.server:443/v3' -backend-config 'tenant_name=ProjectName' -backend-config 'token=gAAAAA...' -backend-config 'region_name=eu-de-1'

Initializing the backend...

Error configuring the backend "swift": You must provide exactly one of DomainID or DomainName in a Scope with ProjectName`

TF_LOG=INFO does not reveal additional information. 

Using OS_AUTH_TOKEN env variable instead of passing via -backend-config leads to the same result. Same behavior for subsequent plan command if not using swift.

Tried setting OS_IDENTITY_API_VERSION explicitly as well, same result.

Please let me know in case additional information would be required to troubleshoot or reproduce the issue - or in case there is something I'm missing.

Thank you very much!

**Comment by hurdigurdi** [comment]
Can anyone confirm if authentication via auth-token is working using Terraform 0.11.3 and provider-openstack 1.2?

Error messages 
**Error configuring the backend "swift": DomainName may not be provided when authenticating with a TokenID`** 
and 
**Error configuring the backend "swift": You must provide exactly one of DomainID or DomainName in a Scope with ProjectName`**
appear to be contradicting

**Comment by hurdigurdi** [comment]
@jtopjian  - thank you for your response.
Unfortunately, this is not the case. I tested without swift as a backend and did run into the same behavior when using a local tfstate-file. In that case, the issue crops up during "apply"

In the meantime, I have tried without DomainName/ID and without ProjectName, which results in no endpoints being found. 

I've looked at vendor/github.com/gophercloud/gophercloud/openstack/client.go - function v3auth in more detail: authenticating via token, I see a new token being generated in this function, but no endpoints being returned from catalog. Authenticating via username/pass (+project and domain), the proper list of endpoints is being returned from catalog.

Using the same token against the openstack python client though, I am able to see all endpoints and query them successfully - so it's neither an permission nor token issue.

**Comment by jtopjian** [comment]
@hurdigurdi Thanks for the clarification.

I'm able to authenticate with a token with the following environment variables:

```shell
$ export OS_AUTH_TOKEN=$(openstack token issue -c id -f value)
$ env | grep OS_
OS_PROJECT_ID=5aa69d9135524fddab887759f3b6c92d
OS_AUTH_TOKEN=gAAAAA...
OS_IDENTITY_API_VERSION=3
OS_AUTH_URL=http://localhost:5000/v3
```

Can you let me know if this helps at all?

**Comment by hurdigurdi** [comment]
Hi Joe (@jtopjian),

yes, this does help indeed. I have always tried passing these options via "-backend-config" switches. Passing the variables you mentioned above as backend-config during "init" does run into the "no endpoint" error, while setting them as environment variables does succeed using ProjectID. 

Also, while specifying the ProjectID via OS env is working (as said, doesn't work to specify -backend-config tenant_id=...), it is not possible to specify the project name instead of ProjectID. 

Specifying
OS_PROJECT_NAME
OS_AUTH_TOKEN
OS_IDENTITY_API_VERSION=3
OS_AUTH_URL=https://my.auth:443/v3
--> You must provide exactly one of DomainID or DomainName in a Scope with ProjectName

So your suggestion helps alot to proceed, thank you! 
But according to the documentation, it should also be possible to specify 
- via -backend-config switches during init --- and/or
- specify PROJECT_NAME instead of ID
