### ISSUE TITLE
Prepend/append openstack provider version into the user agent

### ISSUE THREAD

**Issue by kayrus** [terraform-provider-openstack/terraform-provider-openstack#604]
Not sure whether it is possible, because there is no release constant/variable available in openstack provider.

At the moment it is only:

```
User-Agent: Terraform/0.11.7 gophercloud/2.0.0
```

**Comment by kayrus** [comment]
@jtopjian are you aware about any plans to add `-X $(PKG)/openstack/version.Version=$(git describe --dirty)` as a flag to go while compiling the provider binary?

**Comment by jtopjian** [comment]
Unless there is precedence in another provider plugin, such as AWS, I don't think this will be something we can do.
