### ISSUE TITLE
Volume: handle immutable "metadata" map keys

### ISSUE THREAD

**Issue by kayrus** [terraform-provider-openstack/terraform-provider-openstack#787]
### Terraform Version

terraform v0.12.3

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_blockstorage_volume_v2
- openstack_blockstorage_volume_v3

### Terraform Configuration Files
```hcl
resource "openstack_blockstorage_volume_v3" "test" {
  name  = "test"
  size  = 1

  metadata = {
      foo = "bar"
      #baz = "qux"
      attached_mode = "123"
  }
}

# Attach the volume
resource "openstack_compute_volume_attach_v2" "test_attach" {
  instance_id = "720a4a54-be90-442a-a3ec-d2a4fc9c23be"
  volume_id   = "${openstack_blockstorage_volume_v2.test.id}"
}
```

### Expected Behavior

Terraform should handle a special `attached_mode` medatada map key (and `readonly` as well) and shouldn't  try to remove it. It also should not allow user to set or update this parameter.

### Actual Behavior

If the volume is attached, every `terraform apply` run produces the diff.

### Steps to Reproduce

```hcl
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

openstack_blockstorage_volume_v3.test: Refreshing state... [id=a5e3ecc2-e65f-44d1-91a0-0bb0e2c156e2]
openstack_compute_volume_attach_v2.datavol_attach: Refreshing state... [id=720a4a54-be90-442a-a3ec-d2a4fc9c23be/a5e3ecc2-e65f-44d1-91a0-0bb0e2c156e2]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # openstack_blockstorage_volume_v3.test will be updated in-place
  ~ resource "openstack_blockstorage_volume_v3" "test" {
        attachment        = [
            {
                device      = "/dev/sdd"
                id          = "a5e3ecc2-e65f-44d1-91a0-0bb0e2c156e2"
                instance_id = "720a4a54-be90-442a-a3ec-d2a4fc9c23be"
            },
        ]
        availability_zone = "az1"
        id                = "a5e3ecc2-e65f-44d1-91a0-0bb0e2c156e2"
      ~ metadata          = {
          - "attached_mode" = "rw" -> null
            "foo"           = "bar"
        }
        name              = "test"
        region            = "region1"
        size              = 1
        volume_type       = "cinder"

        timeouts {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### Important Factoids

Cinder API responses, when volume is not attached:

```json
    "metadata": {
      "foo": "bar"
    },
```

Cinder API responses, when volume is attached:

```json
    "metadata": {
      "foo": "bar",
      "attached_mode": "rw"
    },
```

`attached_mode` metadata key is immutable and cannot be changed. In addition there is a `readonly` immutable key: https://github.com/openstack/cinder/blob/ddb78a99286ae7963f4b8ee1d2e5fc1b54a0a4c3/cinder/utils.py#L676

If you create a POST request to update the special key value, Openstack response will return the original `rw` value.

The issue could be fixed in different ways:
* extend the logic in the terraform SDK `diffMap` func: https://github.com/hashicorp/terraform/blob/56e6ff8e51569106b31d06654363edad5783dd1b/helper/schema/schema.go#L1035..L1134
* convert the metadata type from the TypeMap to the TypeSet and apply the logic, discussed in #620

**Comment by nledez** [comment]
Same problem here:
Terraform v0.12.26
+ provider.openstack v1.28.0

And I have a `readonly` attribute too.

```
  ~ resource "openstack_blockstorage_volume_v2" "test_db" {
[...]
      ~ metadata          = {
          - "attached_mode" = "rw" -> null
            "env"  = "test"
          - "readonly"      = "False" -> null
            "type"          = "db"
        }
```

**Comment by kayrus** [comment]
Something similar was introduced in #1781

**Comment by kayrus** [comment]
Not valid anymore. Looks like it was fixed 5y ago.
