### ISSUE TITLE
count in examples is a reserved name

### ISSUE THREAD

**Issue by styk-tv** [terraform-provider-openstack/terraform-provider-openstack#801]
https://github.com/terraform-providers/terraform-provider-openstack/blob/master/examples/multiple-vm-with-floating-ip/variables.tf#L21

```
Error: Invalid variable name

  on variables.tf line 21, in variable "count":
  21: variable "count" {

The variable name "count" is reserved due to its special meaning inside module
blocks.
```

**Comment by nikParasyr** [comment]
This was fixed by https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/892
it can be closed @ozerovandrei (sorry for the spam, going through the issue list)
