### ISSUE TITLE
openstack_lb_pool_v2 resource lacks TERMINATED_HTTPS protocol support and enable-tls parameter

### ISSUE THREAD

**Issue by pmisiak** [terraform-provider-openstack/terraform-provider-openstack#953]
In Octavia you can use a following protocols in loadbalancer pool:
TCP
HTTP
HTTPS
TERMINATED_HTTPS
PROXY
UDP

So terraform resource lacks TERMINATED_HTTPS.

Moreover the terraform resource don't have enable-tls / disable-tls flag parameter.

OpenStack client output:

$ openstack loadbalancer pool create
usage: openstack loadbalancer pool create [-h]
                                          [-f {json,shell,table,value,yaml}]
                                          [-c COLUMN] [--max-width <integer>]
                                          [--fit-width] [--print-empty]
                                          [--noindent] [--prefix PREFIX]
                                          [--name <name>]
                                          [--description <description>]
                                          --protocol
                                          {TCP,HTTP,HTTPS,TERMINATED_HTTPS,PROXY,UDP}
                                          (--listener <listener> | --loadbalancer <load_balancer>)
                                          [--session-persistence <session persistence>]
                                          --lb-algorithm
                                   {SOURCE_IP,ROUND_ROBIN,LEAST_CONNECTIONS,SOURCE_IP_PORT}
                                          [--enable | --disable]
                                          [--tls-container-ref <container-ref>]
                                          [--ca-tls-container-ref <ca_tls_container_ref>]
                                          [--crl-container-ref <crl_container_ref>]
                                          [--enable-tls | --disable-tls]
openstack loadbalancer pool create: error: argument --protocol is required

OpenStack client show command on existing pool with TERMINATED_HTTPS and tls_enabled set to true:

$ openstack loadbalancer pool show 908f765f-ead0-411d-8b8a-4587d801ae79
+----------------------+--------------------------------------+
| Field                | Value                                |
+----------------------+--------------------------------------+
| admin_state_up       | True                                 |
| created_at           | 2019-11-29T13:40:41                  |
| description          |                                      |
| healthmonitor_id     | d2412bb7-b44f-46de-8ad8-c50cf7653f4b |
| id                   | 908f765f-ead0-411d-8b8a-4587d801ae79 |
| lb_algorithm         | ROUND_ROBIN                          |
| listeners            | 432567d6-5cd8-4ddf-8e02-ac80b5477f06 |
| loadbalancers        | c0fc677e-bb78-4fba-aa5d-09629a9fce10 |
| members              | 90a3eb7b-4f2e-4195-9e87-c02cb5f8ff0c |
|                      | 0f5a387d-5846-4532-8282-400caaf8c6a1 |
|                      | adcd5318-877c-4902-86ed-ee2e806bff2b |
| name                 | pool_tls                             |
| operating_status     | ONLINE                               |
| project_id           | cefb973ad2414c18820ae361ce1dc6e3     |
| protocol             | TERMINATED_HTTPS                     |
| provisioning_status  | ACTIVE                               |
| session_persistence  | persistence_timeout=None             |
|                      | cookie_name=None                     |
|                      | type=HTTP_COOKIE                     |
|                      | persistence_granularity=None         |
| updated_at           | 2020-01-07T14:29:03                  |
| tls_container_ref    | None                                 |
| ca_tls_container_ref | None                                 |
| crl_container_ref    | None                                 |
| tls_enabled          | True                                 |
+----------------------+--------------------------------------+

Tested on OpenStack Stein.

**Comment by pmisiak** [comment]
This is needed to create a HTTPS terminated Octavia loadbalancer with HTTPS protocol also for communication with backend servers.

**Comment by dr4Ke** [comment]
The `TERMINATED_HTTPS` seems supported now. It still lacks the `enable-tls` support though.

**Comment by kayrus** [comment]
`TERMINATED_HTTPS` was added in #49
The `enable_tls` pool parameter is already tracked in #1611
