### ISSUE TITLE
Can't set volume quota by volume type

### ISSUE THREAD

**Issue by fobrice** [terraform-provider-openstack/terraform-provider-openstack#979]
Hi,

With `openstack_blockstorage_quotaset_v3` and `openstack_blockstorage_quotaset_v2` we can't set a quota by volume type.

The feature exists with the openstack command:
`openstack quota set --gigabytes <quota> --volume-type <volume_type> <project_id>`

The resource `openstack_blockstorage_volume_v2` already allows the use of [volume_type](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_blockstorage_volume_v2.go#L89) to create a volume.

### Affected Resource(s)
This feature affects:
- openstack_blockstorage_quotaset_v2
- openstack_blockstorage_quotaset_v3

### Expected Behavior
The syntax could be like the `openstack_blockstorage_volume_v2` resource:
```
resource "openstack_blockstorage_quotaset_v2" "quotaset_1" {
  project_id = "${openstack_identity_project_v3.project_1.id}"
  gigabytes = 100
  volume_type = <volume_type>
}
```
Thank you
--
Fabrice

**Comment by ozerovandrei** [comment]
It can be done but support for `volume_type` quota should be added to Gophercloud first.
API docs: https://docs.openstack.org/api-ref/block-storage/v3/?expanded=show-quotas-for-a-project-detail

**Comment by nikParasyr** [comment]
Have opened an [issue on gophercloud](https://github.com/gophercloud/gophercloud/issues/2072) for this.
