### ISSUE TITLE
Openstack Provider - Host Aggregate creation/handling

### ISSUE THREAD

**Issue by LaurentDumont** [terraform-provider-openstack/terraform-provider-openstack#988]
### Terraform Version
./terraform --version
Terraform v0.12.24
+ provider.openstack v1.26.0ed.

### Affected Resource(s)
Please list the resources as a list, for example:
- Openstack Host aggregate

Hi!

Is there any support in Openstack Terraform to handle the creation of host aggregates?

Thanks!

**Comment by antoffka** [comment]
Interested in this Host aggregate handling as well. 
Currently have to "workaround" it with ansible local provisionier using os_nova_host_aggregate module.

**Comment by nikParasyr** [comment]
@ozerovandrei I think this can be closed as it was implemented in #1121 and released in 1.35.0
